### ISSUE TITLE
Generic types and alias

### ISSUE THREAD

**Issue by bhoudebert** [juhaku/utoipa#101]
For some reason it seems that if I use some generic in struct, at some point it does not infer the type and instead expect the generic letter as type.

NB: One thing so, it seems that I cannot declared a type  using genercs over some utopia attribues like `MyStruct<String>` (request_body, value_type etc), seems a parsing error - so I used alias, not a big deal as I already use a lot of them.

```Rust
// This is dummy code, far form as complicated as in our code base but should provide enough insight I hope
type O1 = String;
type O2 = u64;

pub struct MyStruct<T> {
   pub id: String,
   pub content: OtherStruct<T>, // Please not that we could here use also another struct instead of simple alias over primitive types
}

type TopType1 = MyStruct<O1>;

#[openapi(
    handlers(...),
    components(TopType1, ...)
```
It returns something like this
```json
"TopType1": {
  "type": "object",
  "required": [
    "id", "content"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "content": {
      "$ref": "#/components/schemas/T"
    }
  },
  "description": "First round trip from requesting party to ask to build a receipt transaction"
}
```

I could obviously switch to use `impl utoipa::Component for TopType1 {` and all other sub combination (on sub structs using aliases) but as it feels to me a bit overwhelming for an already big app I am wondering if I am missing something on configuration or any property or just not supported yet.

Any insight is welcome, thanks.

**Comment by juhaku** [comment]
Hi, 

This is actually quite hard puzzle to solve. For example if we have following code:
```rust
#[derive(Serialize, Deserialize, Component)]
enum AppStatus {
    Up,
}
// when this `Component` derive executes it need to know the type, since it happens in when macro is compiled
// not when its used.
#[derive(Serialize, Deserialize, Component)]
struct Status<T> {
    status: T,
}

#[utoipa::path(
    responses(
        (status = 200, description = "Get app status", body = Status)
    )
)]
#[get("/status")]
async fn status() -> impl Responder {
    HttpResponse::Ok().json(Status {
        status: AppStatus::Up,
    })
}

// -- within main
#[derive(OpenApi)]
#[openapi(
     handlers(
         status,
     ),
     components(Status<AppStatus>, AppStatus)
)]
struct ApiDoc;
```

This is fundamental difference and usually easily solved in dynamic or more dynamic languages like Java or TypeScript etc. And typically this kind of type reuse is typical in more dynamic languages. Hence there comes 2 major issues to solve.
1. Utoipa is compile time and when `Component` derive macro get executed it need to know the types it is going to use when it writes the OpenAPI documentation. And with generic type `T` it does not know what type it should refer in OpenAPI doc. For example if instead of `T` it would be concrete type like `MyStatus` it would work since it would know which type it should refer in OpenAPI doc. That being said if it was written as follows it would work but then the generic would be completely redundant. Unless it would be used to manage state of object.
```rust
#[derive(Serialize, Deserialize, Component)]
struct Status<AppStatus> {
    status: AppStatus,
}
```
The generics work and are allowed but mainly usable with types using lifetimes or traits. But fields cannot have generic type.

2. With above generic type `Status<T>` which has field with type `T` there is no way know what type to use as value for field in OpenAPI doc. Because every used type needs to have a type declaration within OpenAPI doc that it is able to render the spec and show what the endpoint would return as a response. And from OpenAPI perspective there is no such thing as generic type and if a generic type would be introduced somehow multiple times they all would have same name which is not okay for OpenAPI. Rusts type alias would be pretty good alternative but since type alias does now have its own `Component` derive declaration it renders as copy of the original type. 

Although one way to render generic type in OpenAPI doc is to make generic type `T` or similar to just render as dictionary in OpenAPI (`type: object`) But this is not implemented and would not serve the purpose because idea is to document the api after all and not to tell the person viewing the Swagger UI that it returns something. The dictionary types in OpenAPI are just plain untyped objects and can represent anything. 

However since Rust has amazing type system there is a way around this at least sort of. But it needs changes to the code and desing perspective. Rusts enums are just so good and multipurpose, and these enums can be used to indicate conditional type what the api would return. For example we could have following code:
```rust
#[derive(Serialize, Deserialize, Component)]
enum AppStatus {
    Up,
}

#[derive(Serialize, Deserialize, Component)]
enum Status {
    Health(AppStatus),
    Other(Other),
}

#[derive(Serialize, Deserialize, Component)]
struct Other {
    field: String,
}

#[utoipa::path(
    responses(
        (status = 200, description = "Get app status", body = Status)
    )
)]
#[get("/status")]
async fn status() -> impl Responder {
    HttpResponse::Ok().json(Status::Health(AppStatus::Up))
}

// -- in main
[derive(OpenApi)]
#[openapi(
    handlers(status),
    components(Status, AppStatus, Other)
)]
struct ApiDoc;
```
In above code we have enum Status which can return multiple types. Here `Status` is kind of generic but still all its variants are know at compile time and OpenAPI can also tell that endpoint should return one of objects under the `Status` type.

Yeah currently indeed the type parameters in `value_type` or `request_body` does not support types with generics  e.g. `MyType<String>`. And currently as you already mentioned one way around it is to use type aliases or Rust's new type idiom. like `AnoterType(MyType<String>)`. But currently value_type allows only primitive types at the moment according to OpenAPI datatypes. And request_body and response_body supports indeed a custom format which does not understand generics. Propaby I need take a note of this and see if this can be supported some easy way.

Hope this helps, cheers

**Comment by bhoudebert** [comment]
Thanks for the response and the help.

I would really have though that using type Alias would allow to trick and add dedicated schema entry but as you said It cannot be extended explicitly with a dedicated `component` (is there a world where we could?).

About Enum, I will have to see if it is possible (without too much work), we did not used `sum type` with enum as it was not the target, but really more some struct attributes that could change their type depending on context (it may be also possible to clearly create several struct - still a bit boring and less maintainable - arguable).

If I may, this is something we tried to be closed too, like in Haskell with our generics/aliases.

```haskell
--Haskell
type instance MyType 'BeforeStage1 = ()
type instance MyType 'BeforeStage2 = MySubStruct
type instance MyType 'FinalStage = String

type instance MyOtherType 'BeforeStage1 = Int
type instance MyOtherType 'BeforeStage2 = Float
type instance MyOtherType 'FinalStage = Word64

data MyStruct stage = MyStruct 
  { id :: Uuid,
    content :: MyType stage
    meta :: MyOtherType stage
    -- lots of other fields
  }

-- using in function signature "MyStruct 'BeforeStage1" etc
```

Alas not really possible in Rust without too much fuzz, anyway thanks for the insight I will have something to think about.

**Comment by juhaku** [comment]
Indeed this kind of control flow is bit of a fuzz with Rust but because heavy static typing and compile time checks its not super ergonomic and involves the earlier mentioned generic type which at the other hand cannot be known when macro executes. I take a note to myself and try to see if there is a way to improve this but it would only mean that the type recorded at OpenAPI spec would have only one state there. Which would mean that it could not represent all the possible stages with this state machine pattern. But I wouldn't keep my hopes too high.
