### ISSUE TITLE
5.0.0-rc.0 sets PATCH header as lowercase patch, resulting in 405

### ISSUE THREAD

**Issue by kanpov** [juhaku/utoipa#1085]
5.0.0-rc.0 and scalar 0.2.0-rc.0 for some reason sets a lowercase `patch` instead of `PATCH`, meaning all PATCH requests made from Scalar result in a 405.

**Comment by juhaku** [comment]
That sounds really weird. There is not really changes in `utoipa-scalar` and `utoipa` does not really touch any network related code. All it does it provides the OpenAPI doc basically and `utoipa-scalar` does provide the means to serve the docs.

**Comment by juhaku** [comment]
The scalar is actually served by whatever comes through the CDN:
https://github.com/juhaku/utoipa/blob/33e64c7ffac2809bb46f8c5e32436c92e836330b/utoipa-scalar/res/scalar.html#L17

Still the implementation of this PR https://github.com/juhaku/utoipa/pull/892 is bit naive as it does not allow overriding the HTML file to something else effectively changing the version of scalar (if that's even possible through). 

Nevertheless I believe that the issue lies in the `scalar` itself that is coming via CDN and in changes that they have made to it.

**Comment by juhaku** [comment]
I added PR https://github.com/juhaku/utoipa/pull/1086 to allow customization of Scalar. This allows overriding the default Scalar html template with custom one. e.g. You could enforce Scalar to a specific version if necessary. See more about HTML configuration at https://github.com/scalar/scalar/blob/main/documentation/integrations/html.md.

**Comment by kanpov** [comment]
> I added PR #1086 to allow customization of Scalar. This allows overriding the default Scalar html template with custom one. e.g. You could enforce Scalar to a specific version if necessary. See more about HTML configuration at https://github.com/scalar/scalar/blob/main/documentation/integrations/html.md.

This seemed to be a Scalar issue, and just as a note for anyone that runs into things like these: **delete the cache from jsdelivr in your browser so that Scalar is updated**.
