### ISSUE TITLE
[5.0.0-rc.0] inlined types shouldn't be included in automatic schema collection

### ISSUE THREAD

**Issue by whyando** [juhaku/utoipa#1114]
Right now I noticed that the automatic schema collection is collecting inline types when it shouldn't.

For example PersonRequest is inline in the schema and not referenced at all, so it doesn't need to be added to schemas.

```rust
#[utoipa::path(
    post,
    path = "/api/person",
    request_body = inline(PersonRequest),
    responses(
        (status = OK, body = Person),
    ),
)]
```

(I only started looking at this crate today so it's very possible I've done something wrong though)
thanks

**Comment by juhaku** [comment]
Yeah it does collect them, it does not separate between inline and not inline, it is way easier that way. However I am most likely going to add a config flag to alter this behavior so that by default explicitly inlined schemas are not added, but this behavior could be changed with config flag allowing adding all schemas nevertheless (that can be found as a reference).

However referenced schemas which are not necessarily used anywhere will be still added. Not going to change this.
