### ISSUE TITLE
optional api param in #[openapi(nest(..))]

### ISSUE THREAD

**Issue by ValentinColin** [juhaku/utoipa#1164]
My use case could be a little specific and I don't know if the current impl allow this. 

Currently in my backend, I've 2 front-apis and only one is public. I use 
```rust
axum::Router().nest("api/priv/v1", ..).nest("api/public/v1", ..)
```

In this way, all api paths are truncated at “api/public/v1” in openapi output. I though that Openapi macro with the new `nest` could help but it seems to nest only multiple OpenApi struct. And I don't want to expose all apis in one file.

Do you think it's possible to have
```
nest(
        (path = "api/public/v1") // error: `api = ...` argument is mandatory for nest(...) statement
),
...
```
so all path are prefixed with the path "api/public/v1" ?

**Comment by juhaku** [comment]
I don't think the `api` param can be optional there, because that is what gets nested. It would do nothing without the `api` param. If you want specifically to prefix all paths it should be done manually. E.g. You can see an example here, and doing this in the `Modify` trait implementation or directly to the `OpenApi` should be quite a simple task.
https://github.com/juhaku/utoipa/blob/e9eebd0d191a428203478f35be77ee2a6c1b0352/utoipa-actix-web/src/scope.rs#L212-L221
I don't think that the nest without `api` param is the right place for this kind of functionality, and perhaps there should be some other attribute in `OpenApi` something like `path_prefix` but this again is quite a niche requirement.

**Comment by ValentinColin** [comment]
Indeed you are right.

I tried your solution but the problem in the Modify trait is that even if `openapi: OpenApi` is a mutable reference the `PathsMap` does not provide a mutable reference of the `path: String` but only a simple reference and a mut ref of `PathItem`.

Do I miss something ?

**Comment by ValentinColin** [comment]
I understand now... ApiDoc doesn't have any path because they are added later with tha macro `utoipa_axum::routes!`. Modifiers arn't stored in the OpenApi object to be called later.

**Comment by ValentinColin** [comment]
I manually call the modifier after defining the `routes!`. But it's a little less ideal.

**Comment by ValentinColin** [comment]
I closed
