### ISSUE TITLE
Name variants on enum with ``repr``

### ISSUE THREAD

**Issue by RubberDuckShobe** [juhaku/utoipa#1181]
Hello, I have an enum like this:
```rust
#[derive(ToSchema)]
#[repr(i16)]
pub enum AccountType {
    User,
    Moderator,
    Team,
}
```

In the OpenAPI spec that was generated, it only shows the integers, with no name at all:
![image-67~2](https://github.com/user-attachments/assets/8ec9dfee-f5f7-49af-86a9-d9e785d3404e)

Is there a way to specify the name for enum variants? It'd be great to be able to have the names in the spec as well.

**Comment by juhaku** [comment]
I would say this is a duplicate for this #954. Since enums in general are represented in JSON Schema as `enum: [...]` There is no way to add any description on them. https://json-schema.org/understanding-json-schema/reference/enum.

While this doc is for OpenAPI 3.0 https://swagger.io/docs/specification/v3_0/data-models/enums/ it contains an example of how to leverage a description field to further expand what the enums contains.

**Comment by RubberDuckShobe** [comment]
Thanks for the help, I'll see. Sorry for the duplicate
