### ISSUE TITLE
axum example question

### ISSUE THREAD

**Issue by eventhorizonpl** [juhaku/utoipa#122]
Hi @juhaku 

https://github.com/juhaku/utoipa/commit/e22a5c025eceeb436993ec04c2640b7f9ddce792

I was going to work on this. Can I add your example code to axum repo?

Best regards,
Michal

**Comment by juhaku** [comment]
@eventhorizonpl  Sure thing its free and opensource ;) :D

**Comment by idiomatic-rust-com** [comment]
It's still better to ask first :) Maybe you planed to do it on your own? Ok, I'll send a PR for axum.

I planed to work on this example code as part of my #CrateOfTheWeek contribution. Maybe instead of this I'll check code coverage in tests and improve things where I'll be able?

**Comment by juhaku** [comment]
Yeah. Its good to ask :) You can send a PR to axum. Oh snap. I just wrote the example because it was quick to get out of the way :D 

Well yeah.. I haven't yet checked the coverage over the test that is indeed someting to do though there are tests for different feature flags so getting full report might not be simple or possible? 

Most of the tests there indeed tests the doc generation with macros using integration tests. And less of raw unit tests. So unit test side might be lacking from utoipa side which merely has only Rust types of OpenAPI schema. But sure if that's something you'd like to do go for it :) any contributions are welcome haven't yet though written any contribution "guidelines" but Im pretty easy going with the project. And of course you can further tune the example as well if you like :)
