### ISSUE TITLE
`..utoipa::openapi::PathItem::default()` | error[E0639]: cannot create non-exhaustive struct using struct expression

### ISSUE THREAD

**Issue by SamuelMarks** [juhaku/utoipa#1225]
I want the OpenAPI to also show a few routes that are running non Rust servers. So I tried to manually implement:
```rs
struct NonRust;

impl Modify for NonRust {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        openapi.paths.paths.insert(
            String::from("/api/v1/other"),
            utoipa::openapi::PathItem {
                summary: Some(String::from("Other stuff")),
                get: Some(utoipa::openapi::path::Operation {
                    summary: Some(String::from("Retrieve stuff results")),
                    ..utoipa::openapi::path::Operation::default()
                }),
                post: Some(utoipa::openapi::path::Operation {
                    summary: Some(String::from("Create stuff with `url`")),
                    ..utoipa::openapi::path::Operation::default()
                }),
                ..utoipa::openapi::PathItem::default()
            }
        );
    }
}
```

I suppose I could use `new()` with a fluent syntax, but shouldn't this pattern just work? - It has the advantage of being rather readable and all in one place.

**Comment by juhaku** [comment]
That is a design decision that has been made to avoid possible breaking changes leaking into the user's crates. See here for example https://doc.rust-lang.org/cargo/reference/semver.html#enum-variant-new. It is better for library authors to provide a static unchangeable API if possible. If it was not `#[non_exhaustive]` the above example would work, but then all additions, changes or removes of fields / variants on the type in question would need a major version release which is not very good design just because it potentially would be a breaking change for anyone using the exposed API.

**Comment by SamuelMarks** [comment]
Interesting, I thought `Default::default()` would overcome that issue of changing variables… but ok if Rust recommends it who am I to contradict

**Comment by juhaku** [comment]
> I thought `Default::default()` would overcome that issue of changing variables...

That would overcome it partly, e.g. in case if a new field was added, then it would still work assuming users will use the `Default::default()` But we cannot enforce users to use that syntax, so technically it still would be a breaking change. However `Default::default()` does not cover the case if field type has been changed or if field / variant has been removed. That would still be a breaking change visible to the users, if that field was one of the fields users explicitly defined.
