### ISSUE TITLE
Serde Deserialize parameters

### ISSUE THREAD

**Issue by kellpossible** [juhaku/utoipa#129]
Warp has the function https://docs.rs/warp/latest/warp/filters/query/fn.query.html which accepts query parameters in the form of a type that implements `DeserializeOwned`. It would be good if we could plop this into `params` instead of needing to respecify them manually. Perhaps https://docs.rs/utoipa/1.0.2/utoipa/derive.IntoParams.html could be generalised to fill this role?

**Comment by juhaku** [comment]
Yeah. This basically could be done. However with warp one question relies on how to distinct struct used for query parameters from type used for request body if endpoint accepts both filters. Like with following code since warp uses types as is as arguments to the handler function the context available to the `utoipa::path(...)` derive macro is limited and cannot know which arguments is
used as body and which is used as query. Not like `actix-web` which uses their own wrappers around the types.
 
```rust
warp::any()
    .and(warp::query::<Foo>())
    .and(warp::body::json::<Bar>())
    .map(serve);

#[utoipa::path(...)]
async fn serve(bar: Bar, foo: Foo) {
    ....
}
```
If there is a way to distinct the arguments this could be implemented. Probably with this support I should create warp specific wrapper types which could be used to help to distinct the context similar to actix-web. So then the body would become `Body<Bar>` and query `Query<Foo>`. Another alternative would be if possible to provide attributes to the function arguments to the serve function. But this is not likely possible since the argument level attributes are currently little bit limited in syntax support.

**Comment by kellpossible** [comment]
Perhaps you could add a way to pass the path to a type that implements `IntoParams` an `ParameterIn` into the `params()` macro?

```rust
#[derive(Debug, Deserialize, IntoParams)]
pub struct QueryParams {
    #[param(style = Form, example = json!("task"))]
    contains: Option<String>,
}

impl utoipa::ParameterIn for QueryParams {
    fn parameter_in() -> Option<utoipa::openapi::path::ParameterIn> {
        Some(ParameterIn::Query)
    }
}

let list_path = warp::path!("path" / i64)
    .and(warp::get())
    .and(warp::path::end())
    .and(warp::query::<QueryParams>())
    .and_then(list_impl);

#[utoipa::path(
    path = "path/{arg}"
    params(
        ("arg", ...),
        QueryParameters,
    )
)]
pub fn list_impl(arg: i64, query: QueryParams) -> Result<impl Reply, Infallible>  {
    // ...
}
```

**Comment by juhaku** [comment]
That is pretty good idea. I'll investigate possibilities once I have time to get on this one. And sorry for late reply I have been reaylly busy in these days which had left me no time to spend with improving the library.

**Comment by kellpossible** [comment]
@juhaku no worries! I have been playing with a proof of concept for this might have something to share in a few days.
