### ISSUE TITLE
Support pkce with oauth2

### ISSUE THREAD

**Issue by jgramoll** [juhaku/utoipa#131]
I am trying to use utoipa-swagger-ui with oauth2 (https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/oauth2.md). I need to be able to set the `usePkceWithAuthorizationCodeGrant` flag so that I can authorize with pkce. Is there currently a way to support this or something that could be added?

**Comment by juhaku** [comment]
Yeah, unfortunately the configuration options via `utoipa-swagger-ui` is far limited at the moment. Currently there is no way to configure other than the url(s) for the api docs. 

Support for this could be added and is pretty straight forward to implement. I've had a plans to improve the Swagger UI configuration options but hadn't had time to work on this. I'll add a task to the project's kanban board about this so that it will be done some point in future. Currently there are already quite a few things to work on.
