### ISSUE TITLE
AnyValue {} for third party types

### ISSUE THREAD

**Issue by RemiKalbe** [juhaku/utoipa#162]
Hello again,

I need to use some types that comes from a third party library but obviously they don't implement `#[derive(Component)]`. I looked at the doc and tried to do something like this 
```rust
#[derive(Debug, Deserialize, Component)]
pub struct SampleStruct {
    ...
    #[component(value_type = Object)]
    pub rtp_capabilities: RtpCapabilities,
    ...
}
```
but sadly it stills tries to create a ref to something that doesn't exist
```json
"rtp_capabilities": {
  "$ref": "#/components/schemas/RtpCapabilities"
},
```
what I would like instead is a way to specify that I want any kind of Object in `#[component]`. Obviously it would be better to actually have the correct type, but this would at least create a correct OpenAPI file that I can use.
Or maybe I'm missing something?

**Comment by juhaku** [comment]
Yeah, this is not supported by desing actually. There is no way currently define `object` type and reason for this is that it is not helpful for users to see when they browse the OpenAPI doc or Swagger UI that the endpoint will return `object` which could contain anything. This might be a bit furstrating but for API consumers is a lot more helpful to see the actual types instead of any. If the OpenAPI spec was to be written manually it still has the need to define all the fields of the object.

But a way to get around this is to define type as a `Map` e.g. `HashMap<String, String>` since maps are by OpenAPI spec rendered as `object` types.

Support for this though could be added, but defining just an object is cheating and re-creating a type which has a lot of fields feels annoying.

**Comment by RemiKalbe** [comment]
Yeah I know it's cheating, I'm only using the generated OpenAPI spec to generate a rust client to use internally so it's not really important to me if I have some objects that aren't defined. I suggested this as a simpler solution for the time being; correct serialization of third-party struct would be better of course.

**Comment by juhaku** [comment]
Sure, such a case overriding the actual type as `object` could be reasonable. This is something that need to be addressed in the desing itself. But should not be a big addition though. I'll add note of this to the projects kanban board.

**Comment by juhaku** [comment]
#168 duplicate touches the same matter.
