### ISSUE TITLE
Support namespacing for types which have the same name

### ISSUE THREAD

**Issue by kellpossible** [juhaku/utoipa#186]
One of the main reasons for using namespacing is to separate types without requiring type aliases:

```rust
components(
    crate::mod1::SomeType,
    crate::mod2::SomeType
)
```

Currently this isn't possible with the `openapi` macro, however I can supply these names manually without using the macro. But referencing these components with paths in other macros is also not possible.

As I understand it, this gets a little complicated because, the use case in #152 was to avoid needing to import types, but it still references the component using the final ident in the path `SomeType` which in this situation will cause a clash. 

Perhaps we need to introduce some kind of path name resolution syntax, such as `crate::mod::SomeType as mod::SomeType` so that it does not discard the complete path? 

```rust
components(
    crate::mod1::SomeType as mod1::SomeType,
    crate::mod2::SomeType as mod2::SomeType,
)
```

To the left of the `as` is the path used to get the `Component` implementation, and to the right of the `as` is the path/name to use for the component in the API specification, and to be used for referencing in other macros using the `value_type = mod1::SomeType` attribute.

Related to #152 and #164.

**Comment by juhaku** [comment]
Yes currently the type is resolved from last ident of the expr path:
```rust
components(
    crate::mod1::SomeType
)
```
I would suggest that as mentioned above that we could implement support for casting the type name with `as` keyword. But not necessary add support for path expression after the `as` keyword.

This would be supported:
```rust
components(
    crate::mod1::SomeType as MyCastedType
)
```

But this at the other hand would not be:
```rust
components(
    crate::mod1::SomeType as another::mod::SomeCastedType
)
```
Since the type name is always considered to be the last segment in the expression path thus the `another::mod::` part being irrelevant to my knowledge. 

However not exactly sure how easy this is to support though. And taking in account that I have been considering refactoring the way components names are being registered in OpenAPI components section at the moment. My idea is that the name for the `SomeType` would not be defined by the last segment in the path but instead it would be returned by the `::component()` function call. This allows `serde(rename = ...)` to be used on container level to rename the components.
