### ISSUE TITLE
IntoResponses trait

### ISSUE THREAD

**Issue by kellpossible** [juhaku/utoipa#201]
It would be nice to have an `IntoResponses` trait that works in a similar way to the `IntoParams` trait. 

```rust
trait IntoResponses {
    fn responses() -> Vec<utoipa::openapi::response::Response>
}
```

Personally I would like to create a custom derive of `IntoResponses` for enums that represent different response types on a platform that I'm documenting, and be able to just plug it into the `path` attribute like:

```rust
#[derive(my_macros::IntoResponses)]
enum Response {
    Ok,
    NotFound,
    Forbidden,
}

#[path(
    ...
    responses(Response)
)]
````

This would also work fine for structs which can return a single response:

```rust
#[derive(my_macros::IntoResponses)]
struct Ok;

#[derive(my_macros::IntoResponses)]
struct NotFound;

#[derive(my_macros::IntoResponses)]
struct Forbidden;

#[path(
    ...
    responses(
        Ok,
        NotFound,
        Forbidden,
    )
)]
````

**Comment by juhaku** [comment]
This would be indeed a great addition to the library. It would allow users to break down the `path` documentation in smaller and more manageable pieces which helps in reusability. This is definitely something that could be addressed in future.

**Comment by kellpossible** [comment]
I guess consideration must also be given to people who want to use references to response components. It looks like there is not currently a way to store these components in the API but hopefully there will be in the future. A reference can only reference a single response component, therefore:

`responses(Response)` can only reference a single component, same with `responses(inline(Response))`. Perhaps it would be better to work on the response component implementation first before considering this proposal again, and perhaps altering it slightly to make the interface consistent?

**Comment by kellpossible** [comment]
Alternatively, in the future when the response components get implemented, there could be a second new trait called `IntoResponse`, which can be used like this:

```rust
responses(
    (ResponseOne),
    (ResponseTwo),
    (ResponseThree),
)
```
If it falls inside the brackets then it is an `IntoResponse`, they are references by default, but can be inlined. If there are no brackets, then it is an `IntoResponses`.

**Comment by juhaku** [comment]
> I guess consideration must also be given to people who want to use references to response components. It looks like there is not currently a way to store these components in the API but hopefully there will be in the future. A reference can only reference a single response component, therefore:

> `responses(Response)` can only reference a single component, same with `responses(inline(Response))`. Perhaps it would be better to work on the response component implementation first before considering this proposal again, and perhaps altering it slightly to make the interface consistent?

Certainly this haven't been given enough thought previously and hasn't been held high on priorities. The OpenAPI spec supports having `responses` and even `parameters` beside the `components` in the document and use them via references similarly how components are now being used. This however is not implemented at the moment. If we wanted to add support for referenced responses we probably need to implement `responses(..)` support for `OpenApi` derive macro.

```rust
#[derive(IntoResponses)]
struct MyResponse {
     // ....
}

#[derive(OpenApi)]
#[openapi(
    responses(MyResponse)
)]
struct ApiDoc;


#[utoipa::path(
    responses(
        MyResponse
    )
)]
fn get_foo() {}
```

> ```rust
> responses(
>    (ResponseOne),
>    (ResponseTwo),
>    (ResponseThree),
>)
>```

Not a super fan of having multiple different ways to define responses. Less variables its easier for users to remember the syntax. Since `components` and `parameters` are already defined in consistent way its hard for me to concur to introduce yet another syntax using parenthesis.

```rust
components(
   Component
)

params(
    MyParams,
    MoreParams
)
```

Instead I wonder whether it's possible to another trait to implement or extend another trait. For example if we had `IntoResponse` trait and `IntoReponses` trait then perhaps `IntoResponse` trait could implement `IntoResponses` trait. Alternatively only have `IntoResponses` trait because we will know whether the type decorated with `IntoResponses` trait is enum or struct so we can determine the needed functionality to implement the responses. For example from enum we can return a response for each variant and for a struct we can return one response but in both cases we could serve them through the same trait implementation.  

```rust
trait IntoResponses {
    fn responses() -> Vec<utoipa::openapi::Response>;
}
```

**Comment by kellpossible** [comment]
@juhaku in terms of updating the `OpenApi` derive macro, I'm thinking that `components()` is a little misleading in its current configuration, because technically there are many different kinds of components, and what is being specified currently is actually `schemas`.

Perhaps `components()` could be modified to something like this?

```rust
components(
    schemas(
        ...
    ),
    responses(
       ...
    )
)
```

This would be a breaking change, but it does follow the specification a little more closely I think.

**Comment by kellpossible** [comment]
> Not a super fan of having multiple different ways to define responses. Less variables its easier for users to remember the syntax. Since components and parameters are already defined in consistent way its hard for me to concur to introduce yet another syntax using parenthesis.

I also agree, I'm not really a fan, also usually parenthesis does not change the meaning of a statement, so this would be strange.

> Instead I wonder whether it's possible to another trait to implement or extend another trait. For example if we had IntoResponse trait and IntoReponses trait then perhaps IntoResponse trait could implement IntoResponses trait. Alternatively only have IntoResponses trait because we will know whether the type decorated with IntoResponses trait is enum or struct so we can determine the needed functionality to implement the responses. For example from enum we can return a response for each variant and for a struct we can return one response but in both cases we could serve them through the same trait implementation.

I'll have a play with just implementing `IntoResponses` and see how if feels.

**Comment by kellpossible** [comment]
Okay, I think we need a trait that will return a `Response` mapped to a name for the response reference to be used for the component in the `openapi` macro, and we need another trait that will return `Response`s mapped to response codes to be used in `path` macro. We can't use the same trait I don't think. 

```rust
trait IntoResponse {
     /// Returns a map of response name to response
    fn response() -> (String, Response)
}

trait IntoResponses {
     /// Returns a map of response code to responses
    fn responses() -> BTreeMap<String, Response>
}
```

**Comment by kellpossible** [comment]
In addition to the `IntoResponses` `responses(MyResponsesEnum)`, I think also then we could allow the `IntoResponseComponent` to be referenced like:

```rust
responses(
    (status = "200", response = MyResponse)
)
```

They could also perhaps be inlined with:

```rust
responses(
    (status = "200", response = inline(MyResponse))
)
```

**Comment by cemoktra** [comment]
Hi, we are currently considering between utoipa and poem. What i like in poem is the way responses are handled. Compare the example: https://github.com/poem-web/poem/blob/master/examples/openapi/todos/src/main.rs#L30

It forces you to add status code mapping, while here it seems its possible to forget about status codes that might be missing in the documentation.

So maybe it's more about the return type must implement `IntoStatusCode` or something

**Comment by juhaku** [comment]
Yeah that looks good. I also had a plan eventually support syntax similar to that.
```rust
#[derive(IntoResponses)]
enum Response {
   #[response(status = 200, ...)]
    Ok,
    NotFound,
    Forbidden,
}

#[path(
    ...
    responses(Response)
)]
```
And possibly with single response as.
```rust
#[derive(Response)]
#[response(status = 200, ....)]
struct Response;

#[path(
    ...
    responses(
        inline(Response)
    )
)]
```
Or without inline it will create a reference which then requires it to be added to the openapi responses list.
```rust
#[path(
    ...
    responses(
        Response
    )
)]
asyn fn handler() {}

// ................ elsewhere the the openapi is defined
#[openapi(
   components(
       responses(
           Response
        )
   )
)]
```

**Comment by cemoktra** [comment]
That would be really nice. We would like to use axum but I fear forgetting about return codes when it's a free attribute

**Comment by juhaku** [comment]
Yeah.. Seems like in poem it is also possible to provide status as a free form text like below.
```rust
#[derive(ApiResponse)]
enum GetResponse {
    #[oai(status = 200)]
    Todo(Json<Todo>),

    #[oai(status = 404)]
    NotFound(PlainText<String>),
}
```

The thing is that the status need to be given in some possible way for the OpenAPI doc. There is also plan in future to support resolving response and and status from the return value of the handler function for frameworks like actix-web, axum and rocket. But the support would be very limited. Theoretically the response 200 would be the return value and if return value is a result with error `Result<Success, Error>` then the default error response like 500 could also be resolved. But that might not be the actual error status that should be resolved. By looking the return values and guessing responses gets really hard.  

Also relying on return type is hardly a framework agnostic thus is not beneficial for the library itself and would make it harder to maintain because of a need to keep track on upcoming changes of every framework. 

We could expect the return value or the response entity implement `IntoStatusCode` trait for resolving the status code for the response in the doc but if expected the handler return value implement the trait we could not support the cases where the handler would return multiple different status codes which are separate responses. Then the different response cases still needs to be given to the path macro.
```rust
#[derive(Response)
struct Response1;

impl IntoStatusCode for Response1 {
    fn status() -> u16 { 200 }
}

#[path(
    responses(
       Response1, Response2
    )
)]
```

Or there could be a set of deriveable statuses like `IntoSuccess`, `IntoNotFound` for common statuses. And all of those could implement the `IntoStatusCode` trait and we could enforce the `IntoStatusCode` to be implemented and if not it would be a compile error. But the same time we could enforce the `#[response(status = 200)]` parameter to be given and missing it would be a compile error. Currently the API is quite permissive but in future it could be more restrictive but should not be more than the OpenAPI spec itself allows. Like if responsenses can be left out, we should not require user to provide them.

Surely there is caveats in each approach. For what comes to the poem it is a web framework build from ground up for the OpenAPI documentation purpose. The goals of this library is being small, pluggable and framework agnostic (but extendable) allowing users to use the library with or without a framework. This indeed leads certain design issues that cannot be addressed as a library but would need more native approach to gain even smoother user experience. Over time surely many of these sharp edges can be smoothened to almost native level though but to that we need users and their opinions and then people willing to help to build the library. :)

**Comment by cemoktra** [comment]
Yeah I see and understand the point. Also Success does not necessarily mean 200.
Poem has the point there, I guess I will have to write some proof of concepts to make a decision.
