### ISSUE TITLE
Move from `dirs` crate to `dirs-next`

### ISSUE THREAD

**Issue by BastienVigneron** [juhaku/utoipa#272]
Alert from cargo deny :

```
warning[A003]: dirs is unmaintained, use dirs-next instead
   │ ---------------------------------------------------------------- unmaintained advisory detected
   │
   = ID: RUSTSEC-2020-0053
   = Advisory: https://rustsec.org/advisories/RUSTSEC-2020-0053
   = The `dirs` crate is not maintained any more;
     use [`dirs-next`](https://crates.io/crates/dirs-next) instead.
   = Announcement: https://github.com/dirs-dev/dirs-rs
   = Solution: No safe upgrade is available!
   = dirs v4.0.0
     └── shellexpand v2.1.2
         └── rust-embed-impl v6.2.0
             └── rust-embed v6.4.0
                 └── utoipa-swagger-ui v2.0.1
```

**Comment by juhaku** [comment]
Thanks for the info. Seems like previously `shellexpand` has dependency to `dirs-next` in `2.1.0` version, but since then it has reverted back to the `dirs` in the latest `2.1.2` version.

Perhaps you could try to downgrade to the specific `shellexpand` version:
```toml
[dependencies]
shellexpand = "2.1.0"
```

Also maybe it is not a bad issue to report this issue to the maintainer as well https://gitlab.com/ijackson/rust-shellexpand

**Comment by juhaku** [comment]
Taking a deeper look at this. The warning is false positive, and since ever withdrawn and should be ignored. Check the https://rustsec.org/advisories/RUSTSEC-2020-0053 which states following:
> This advisory has been withdrawn and should be ignored. It is kept only for reference.

The `dirs` crate is actually released 12 months ago and the `dirs-next` is released nearly 2 years ago. Not sure though how to get rid of the warning, but perhaps there is a way to ignore certain warnings with cargo deny?
