### ISSUE TITLE
Schema derivation for internally tagged enums

### ISSUE THREAD

**Issue by michaelmattig** [juhaku/utoipa#285]
I see two issues with the current derivation of the schema for internally tagged enums:

1. Utoipa doesn't create a discriminator object 
2. The type field is not created for newtype-variants

Regarding the first issue: The OpenAPI specification (https://swagger.io/specification/ ) says

> When request bodies or response payloads may be one of a number of different schemas, a discriminator object can be used to aid in serialization, deserialization, and validation. The discriminator is a specific object in a schema which is used to inform the consumer of the specification of an alternative schema based on the value associated with it.

Utoipa should be able to create this discriminator object from the serde typetag and add a mapping from the type-strings to the schema object.

As I see it, utoipa still does it "the old way", where an enum is represented as a a OneOf schema and the property that determines the variant is represented as an enum with a single value. However, there seems to be a bug where this property isn't generated for variants that are newtypes:

Here is an example:

```rust
#[derive(serde::Serialize, utoipa::ToSchema)]
#[serde(tag = "type")]
enum Foo {
    Bar,
    Baz(Baz),
}

#[derive(serde::Serialize, utoipa::ToSchema)]
struct Baz {
    a: String,
}
```

and here an excerpt from the generated openapi.json:

```json|
{
"components": {
    "schemas": {
      "Baz": {
        "type": "object",
        "required": [
          "a"
        ],
        "properties": {
          "a": {
            "type": "string"
          }
        }
      },
      "Foo": {
        "oneOf": [
          {
            "type": "object",
            "required": [
              "type"
            ],
            "properties": {
              "type": {
                "type": "string",
                "enum": [
                  "Bar"
                ]
              }
            }
          },
          {
            "type": "object",
            "properties": {
              "Baz": {
                "$ref": "#/components/schemas/Baz"
              }
            }
          }
        ]
      }
    }
  }
}
```

As you see, the `Bar` variant has a property `type` which is an enum with a single value `"Bar"`. However the `Baz` variant has no `type` field.

So the questions are:
 - is it planned to support a proper `discriminator` for enums, and
 - am I right in the current implementation that the newtype schema is wrong?

Please tell me if you would rather have me open two separate issues for this.

Thanks!

**Comment by juhaku** [comment]
> is it planned to support a proper discriminator for enums, and

Currently there has not been any initiatives regarding the implementaiton of `discriminator` field but surely could be added, since currently it is missing from the implementation.

> am I right in the current implementation that the newtype schema is wrong?

Yes you are absolutely right, the generated spec for the `Baz` seems like one what it suppose to generate without the serde tag `type`. The enum spec generation at it's current state is unnecessary complex and not its best condition at the moment. There is definitely room to improve and generalize the implementation. 

> Please tell me if you would rather have me open two separate issues for this.

There is no need to create a two separate issues regarding this but this can be used as a tracking issue for implementing / fixing both of cases. And the possible PRs can be linked here to this issue :slightly_smiling_face:

**Comment by juhaku** [comment]
@michaelmattig My next goal is to rework on these enums in hopes to get some clarity over the current implementation. With this I try also address the issues currently exisitng as you raised up the concern.

**Comment by juhaku** [comment]
Seems like the new type variant with type reference will produce invalid OpenAPI spec document. The snippet  below will result `should be object` error.
```yaml
      - type: object
        title: Unnamed
        properties:
          $ref: '#/components/schemas/Pet'
          tag:
            type: string
            enum:
              - Unnamed
```
![image](https://user-images.githubusercontent.com/26358664/190694367-0ecf26c9-06fb-4491-882d-0cbb413c8901.png)

And even just a reference object with tag is incorrect spec:
```yaml
      - $ref: '#/components/schemas/Pet'
        tag:
          type: string
          enum:
            - Unnamed
```
But `object` with `$ref` field would be correct specification it is still incorrect since it does not match to the corresponding enum structure:
```yaml
      - type: object
        properties:
          $ref:
            $ref: '#/components/schemas/Pet'
          tag:
            type: string
            enum:
              - Unnamed
```

While this would be correct representation, it is not possible at the moment because of missing feature #120. The linked feature should be first implemented to support object flattening in specifications.
```yaml
      - allOf:
          - $ref: '#/components/schemas/Pet'
          - type: object
            title: Unnamed
            properties:
              tag:
                type: string
                enum:
                  - Unnamed
```

The flatteting is not necessary for primitive types and other types which are not references to other schemas. See example with string variant however this also currently produces incorrect schema. The first `type` should be here `object` but is `string`. But this might be easy to quick fix but better solution should be preferred for long run. 
```json
{
      "type": "string",
      "required": [
        "tag"
      ],
      "properties": {
        "tag": {
          "type": "string",
          "enum": [
            "UnnamedString"
          ]
        }
      }
    },
```

As a conclusion for the new type variant I'll add compiler error if new type variant is used with object reference (not a primitive type which typically is a thrid-party type or some type that implements `ToSchema` trait) And if it a primitive type e.g `bool` `String` `i64` I'll add a quick fix for now. Better solution should be done once the flatten support (#120) is implemented so we can also  support references within new type variant when serde `tag` is provided.
