### ISSUE TITLE
Extend Swagger Ui url function to handle other data structures like json or string, not only utopia struct OpenApi

### ISSUE THREAD

**Issue by nedlukasz** [juhaku/utoipa#293]
The SwaggerUi url function takes only OpenApi struct. For example:
```
#[derive(OpenApi)]
 struct ApiDoc;
SwaggerUi::new("/swagger-ui/{_:.*}").url("/openapi.json", ApiDoc::openapi())
```
Swagger Ui do not process anywhere in code OpenApi struct besides serialization it to json when server send response.
It will be very usefull to have function **url_json_doc** that takes json as argument for example:
```
SwaggerUi::new("/swagger-ui/{_:.*}").url_json_doc
```

That api allow to change openapi doc before sending it to SwaggerUi for example:
1. Using utoipa create api doc
2. Serialize api doc to json
3. Extra json modification for example adding to SecurityScheme x-tokenName id_token (utoipa do not support that)
4. Passing to SwaggerUi modified json not original one

**Comment by juhaku** [comment]
Hi,

What kind of API you would be in a need for? There is already `Modify` trait which allows you to modify the generated OpenAPI doc runtime before it is being served. You can find more about it at the docs: https://docs.rs/utoipa/latest/utoipa/trait.Modify.html or even any of the [examples](https://github.com/juhaku/utoipa/tree/master/examples).

Also the api doc created with `OpenApi` trait is a `OpenApi` struct. Before you serve the OpenAPI with the `SwaggerUi` you can modify it as any rust code. E.g.
```rust
#[derive(OpenApi)]
struct ApiDoc;

let mut doc = ApiDoc::openapi();
// ... then do what ever you would like with the doc.
```

There is a builder's for the `OpenApi` struct and other Rust openapi types. See here: https://docs.rs/utoipa/latest/utoipa/openapi/index.html

Since the OpenApi struct like other rust types implements `From<...Builder> for T` https://docs.rs/utoipa/latest/utoipa/openapi/struct.OpenApi.html#impl-From%3COpenApi%3E-for-OpenApiBuilder you convert the `OpenApi` type to `OpenApiBuilder` as seen below and use the builder api.
```rust
let mut doc: OpenApi = ApiDoc::openapi();
let builder: OpenApiBuilder = doc.into();
```

**Comment by nedlukasz** [comment]
Hi Juha
I want to use utoipa-swagger-ui with json (serde_json) but without utoipa structures (because I like the way how crate utoipa-swagger-ui setup boilerplate code for swagger, keeps all dependencies inside crate and create endpoints for different kinds of rust web server).
Problem is that inside rust code utoipa-swagger-ui force me to use utoipa structures (I speak about url function).

In my use case I have OpenApi doc created from utoia and also OpenApi json generated by python script and I want process both of them (in rust code) and serve both of them using Rust api from utoipa-swagger-ui.

The trait that you suggest for processing (Modify) still require using utoipa structures, what I need is processing doc that is already serialized to serde_json.

**Comment by juhaku** [comment]
Okay, I see the point. The `url(...)` and `urls(...)` functions could be extended to support this behaviour and it shouldn't be too big change. I'll try out the possible solutions soon.

**Comment by juhaku** [comment]
@nedlukasz Support for this is coming in next release. There is a PR now  #502 which implements this support.
