### ISSUE TITLE
Use component response in path responses list

### ISSUE THREAD

**Issue by jacob-pro** [juhaku/utoipa#300]
So I have defined a re-usable response using the `OpenApi` macro:

```
        responses(
            api::error::ApiError,
        )
```

Where I have implemented:

```rust
impl ToResponse for ApiError {
    fn response() -> (String, Response) {
         ...
    }
}
```

I would now like to be able to use it in my paths, e.g. something like:

```rust
#[utoipa::path(
    post,
    responses(
        (status = 200, description = "Success", body = ListObjects),
        (status = "default", response = ApiError),
    ),
)]
```

As far as I can see this isn't currently possible right now? (Unless I have to manually create a custom `IntoResponses` for every single path?)

**Comment by juhaku** [comment]
Yeah, there is a already closed discussion regarding this. The derive implementation is unimplemented for responses at the moment.  See more here https://github.com/juhaku/utoipa/issues/201. Though the traits are in place somehow, but might need some tuning once the actual derive implementation gets there. 

I believe there are some people how use the existing traits to build macro rules to imitate the derive functionality partly. 

Eventually when this gets implemented, it should be feasible to just define the response itself within the `responses(...)` attribute.
```rust
#[utoipa::path(
    post,
    responses(
        (status = 200, description = "Success", body = ListObjects),
        ApiError
    ),
)]
```

**Comment by jacob-pro** [comment]
Sorry I'm not sure I quite follow... The status code is still needed though?

E.g. the end spec would look like:

```yaml
  /users/{id}:
    get:
      summary: Gets a user by ID.
      response:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'   # <-----
        '404':
          $ref: '#/components/responses/NotFound'       # <-----
```

so we would need some syntax of mapping a code to the response?

If you have an idea of a syntax which would be acceptable I would be happy to look at writing a PR?

**Comment by juhaku** [comment]
Supporting derivation of responses is not a small feature and I hope to be able to refactor he codebase a bit before adding them to mitigate furhter fragmentation of the code and reduce unnecessary duplication in some areas. Like now there is almost 2 similar implementations `IntoParams` and `ToSchema` but are still different since they serve different purpose, but both of them share a same ideology with the new `IntoResponses` or also perhaps `ToResponse` derive implementation. 

While they would not be completely same, but similary structure from the main parts would be present. 

This is something that should be added in the future. But for now I haven't had the time to invest in implementing this feature.

**Comment by juhaku** [comment]
> so we would need some syntax of mapping a code to the response?

The syntax I was after is demonstrated in this comment: https://github.com/juhaku/utoipa/issues/201#issuecomment-1202622480

**Comment by jacob-pro** [comment]
what about as a first step, expanding the [ToResponse](https://docs.rs/utoipa/latest/utoipa/trait.ToResponse.html#) trait to also return a status code?

This would then allow us to support this syntax?

```
#[utoipa::path(
    post,
    responses(
        (status = 200, description = "Success", body = ListObjects),
        ApiError
    ),
)]
```

**Comment by juhaku** [comment]
> what about as a first step, expanding the [ToResponse](https://docs.rs/utoipa/latest/utoipa/trait.ToResponse.html#) trait to also return a status code?

Sure it could be something like this:
```rust
// define status code somewhere where the responses are defined in utoipa create
pub enum StatusCode {
   // this should be flattened otherwise there not much point with the enum. Should be doable I suppose.
   Number(i32),
   1xx,
   2xx,
   3xx,
   4xx,
   5xx,
   Default,
}

pub trait IntoResponses {
    fn status_code() -> StatusCode;  
    fn responses() -> BTreeMap<String, Response>;
}
```

This way it will not break existing functionality, it could be so that it even would return `StatusCode::Default` as a default status. e.g.
```rust
pub trait IntoResponses {
    fn status_code() -> StatusCode {
         StatusCode::Default
    }
    fn responses() -> BTreeMap<String, Response>;
}
```

**Comment by juhaku** [comment]
Or for simpliest way to do it without any validation is to return str
```rut
fn status_code() -> &'static str {
    "default"
}
```

**Comment by jacob-pro** [comment]
I assume you mean for `ToRespones`? `IntoResponses` already has the status codes but is meant for a collection of responses?

Also the next problem is how would the macro know the difference between:

Where ApiError: ToResponse

```rust
#[utoipa::path(
    post,
    responses(
        (status = 200, description = "Success", body = ListObjects),
        ApiError
    ),
)]
```

and MyResponse: IntoResponses:

```rust
#[utoipa::path(
    post,
    responses(MyResponse)
)]
```

**Comment by juhaku** [comment]
> I assume you mean for ToRespones? 

Yeah I mean `ToResponse`

> Also the next problem is how would the macro know the difference between:

Oh man, true it cannot know it at compile time. Only way would be to move that decision to runtime but with `downcast_ref` but that is not feasible in this situation. This effectively needs a round of thought before its implemented. I went back to an old discussions and found out few suggestions. On one hand it could be implemented as stated here in this comment: https://github.com/juhaku/utoipa/issues/201#issuecomment-1173199430 and in addition it could be implemented as suggested here: https://github.com/juhaku/utoipa/issues/201#issuecomment-1180771424

Thing is that there already is attribute `inline(...)` which is used in `ToSchema` and `IntoParams` derive implementations to potentially inline the schema what would otherwise by default be a reference. So it would make sense to have the definition consistent. 

This  `ref` idea is not bad, this is actually pretty good, but how should the definition be if user wants to inline the response instead of  using reference?. But at the other hand the `ref` is correct according to the OpenAPI schema. 
> ```rust
> #[utoipa::path(
>    post,
>    responses(
>        (status = 200, description = "Success", body = ListObjects),
>        (status = "default", ref = ApiError),
>    ),
> )]
>```
