### ISSUE TITLE
Allow the the statuscode in the `path` macro to be a `http::StatusCode`?

### ISSUE THREAD

**Issue by nerdypepper** [juhaku/utoipa#301]
Currently, the statuscode in the `utoipa::path` macro is either an integer literal, or a wildcard string of the form `"5XX"`. Could we support `http::StatusCode`s too?

Present:

```
#[utopia::path(
    responses(status = 200, description = "Success")
)]
```

What I hope to introduce:

```
use http::StatusCode;

#[utopia::path(
    responses(status = StatusCode::OK, description = "Success")
)]
```

---

`http::StatusCode` supports `ToString` as well as `Into<u16>` which can be used to implement the conversions. I'd be willing to pick this up, if this is something that `utoipa` would like to have!

**Comment by juhaku** [comment]
Sure, definitely could be added :+1:  I have thought this, but haven't done anything to it since in OpenAPI doc the status need to be represented as a numberish string. :smile: 

Adding this capability is not super big thing but need be allowed to opt out / in based on user preferences. I reckon there should be a feature flag `http_status` or something similar what would enable the http status code statuses for the response. Then in here https://github.com/juhaku/utoipa/blob/master/utoipa-gen/src/path/response.rs#L69..L83 we need to check whether type is `TypePath and contains a segment `StatusCode`.

**Comment by nerdypepper** [comment]
I agree about the feature flag, I'll try to open a PR for this!
