### ISSUE TITLE
SchemaFormat should be an open value

### ISSUE THREAD

**Issue by jacob-pro** [juhaku/utoipa#307]
According to the spec:
https://swagger.io/docs/specification/data-models/data-types/#string

> However, format is an open value, so you can use any formats, even not those defined by the OpenAPI Specification, such as:
    - email
    - uuid
    - uri
    - hostname
    - ipv4
    - ipv6
    - and others

I would like to be able to use some of these custom format using the `#[schema(format="")]` annotation, however SchemaFormat appears to currently limited to a [hardcoded enum](https://docs.rs/utoipa/latest/utoipa/openapi/schema/enum.SchemaFormat.html)?

**Comment by juhaku** [comment]
Right, this true, currently it is limited to the hard coded enum, which does not have custom options. Adding possibility to use a custom format would not be a massive enhancement to do. The enum itself could have `Custom` option and parsing of `format` could be made conditional either literal string which would become `Custom` and otherwise any or hard coded values like now.
```rust
enum SchemaFormat {
    Custom(String),
}
```

**Comment by jacob-pro** [comment]
My concern with this is maintaining de-serialization compatibility - because as far as I can see deserializing other values is not currently supported in serde itself: https://github.com/serde-rs/serde/issues/912

There is some discussion and work-arounds here: https://stackoverflow.com/questions/57469527/how-can-i-support-an-unknown-or-other-value-for-a-serde-enum

One way to do it is to write our own `From<String>` and use the `serde(from="String")` annotation - would that be ok with you?

**Comment by jacob-pro** [comment]
same problem for serialization as well I think

**Comment by juhaku** [comment]
Yeah, I think this needs an experiment. I believe there is a way which need to be tested though. Key point in example below is to define `untagged` to the enum representation.
```rust
#[derive(Serialize, Deserialize, Clone)]
#[cfg_attr(feature = "debug", derive(Debug))]
#[serde(rename_all = "lowercase", untagged)]
pub enum SchemaFormat {
    // ... other format options
    /// Custom schema format which is not one of the defaults.
    Custom(String),
}
```
If that does not avail perhaps we need to introduce another `enum` with the current `SchemaFormat`. This `Format` enum would be `untagged` instead of the `SchemaFormat` being untagged. The order of the variants within the `Format` is important since that is the visit order for visitor implementations generated by the serde. We want it first to try out to parse `SchemaFormat` and then on error just parse any string as `Custom`. 
```rust
#[derive(Serialize, Deserialize)
#[serde(untagged)]
enum Format {
    SchemaFormat(SchemaFormat),    
    Custom(String),
}
```

This would work supposedly because `untagged` for `Format` would serialize underlying type of a variant instead thus resulting correct OpenAPI schema. But since they are all serialized as strings within OpenAPI schema there is a slight chance when deserialized they all end up being deserialized as `Custom` which of course would be bummer.

**Comment by jacob-pro** [comment]
#### First Idea

The first method of untagged unfortunately does not work - for either serialization or deserialization.

```rust
#[derive(Serialize, Deserialize, Clone, Debug)]
#[serde(rename_all = "lowercase", untagged)]
pub enum SchemaFormat {
    Int32,
    Custom(String),
}

fn main() {
    println!("Serialize int32 = {}", serde_json::to_string(&SchemaFormat::Int32).unwrap());
    println!("Serialize email = {}", serde_json::to_string(&SchemaFormat::Custom(String::from("email"))).unwrap());
    println!("\"int32\" = {:?}", serde_json::from_str::<SchemaFormat>("\"int32\""));
    println!("\"email\" = {:?}", serde_json::from_str::<SchemaFormat>("\"email\""));
}
```

Output:

```
Serialize int32 = null
Serialize email = "email"
"int32" = Ok(Custom("int32"))
"email" = Ok(Custom("email"))
```

#### Second Idea

The second approach works though and will match to the typed values where possible because when untagged is enabled

> Serde will try to match the data against each variant in order and the first one that deserializes successfully is the one returned.

```rust
#[derive(Serialize, Deserialize, Clone, Debug)]
#[serde(rename_all = "lowercase")]
pub enum SchemaFormat {
    Int32,
    Int64,
}

#[derive(Serialize, Deserialize, Debug)]
#[serde(untagged)]
enum Format {
    SchemaFormat(SchemaFormat),
    Custom(String),
}

fn main() {
    println!("Serialize int32 = {}", serde_json::to_string(&Format::SchemaFormat(SchemaFormat::Int32)).unwrap());
    println!("Serialize email = {}", serde_json::to_string(&Format::Custom(String::from("email"))).unwrap());
    println!("Deserialize \"int32\" = {:?}", serde_json::from_str::<Format>("\"int32\""));
    println!("Deserialize \"email\" = {:?}", serde_json::from_str::<Format>("\"email\""));
}
```

Output:

```
Serialize int32 = "int32"
Serialize email = "email"
Deserialize "int32" = Ok(SchemaFormat(Int32))
Deserialize "email" = Ok(Custom("email"))
```

I am happy to move ahead with implementing via the second approach if this is how you want it done?

**Comment by juhaku** [comment]
I am fine with the second approach. That is probably the only way to get it to support both custom value and static typing.
