### ISSUE TITLE
multiple return types

### ISSUE THREAD

**Issue by the4thfloor** [juhaku/utoipa#308]
Hi, 

I have not found a way to declare a `path` `response` with multiple bodies (`body`) depending on the `content_type` like this:

```json
{
  "paths": {
    "/user": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "get a user",
        "operationId": "getUser",
        "responses": {
          "default": {
            "description": "successful operation",
            "content": {
              "application/vnd.user.v1+json": {
                "schema": {
                  "$ref": "#/components/schemas/UserV1"
                }
              },
              "application/vnd.user.v2+json": {
                "schema": {
                  "$ref": "#/components/schemas/UserV2"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

I have this macro:
```rust
#[utoipa::path(
    get,
    path = "/",
    responses(
        (
            status = 200,
            content_type=["application/vnd.user.v1+json", "application/vnd.user.v2+json"],
            description = "successful operation",
            body = [User],
        )
    ),
)]
```

How can I add another body type?

**Comment by juhaku** [comment]
Hi, this is unfortunately impossible by now. This would need breaking changes to the macro code itself to allow this behavior and most necessary some design work regarding it. 

The current implementation expects only one body type which is then exposed via different content types e.g. `application/json` and `text/xml` but does not allow specifying different response body based on content type. Idea has been that the response body would be the same but is only serialized differently versus the case that content type would determine the response body type itself. Such a scenario has not been taken into account, since typically a new endpoint would be created for different response type e.g `/api/v2/person`. 

I am happy to support this functionality in further releases.

**Comment by the4thfloor** [comment]
Would this be an option?
```rust
#[utoipa::path(
    get,
    path = "/",
    responses(
        (
            status = 200,
            content_type = "application/vnd.user.v1+json",
            description = "return User version 1",
            body = [UserV1],
        ),
        (
            status = 200,
            content_type = "application/vnd.user.v2+json",
            description = "return User version 2",
            body = [UserV2],
        ),
    ),
)]
```

I can do this right now, but it only takes the last one :-( 
But maybe you can merge both together?

**Comment by juhaku** [comment]
Not a bad idea. I need to see whether merging would be an option. With that as well there is some changes needed to the macro generation code. This needs some investigation how the merging could be done. Whether it can be done upon compilation in macro side already or is it done on generated code itself. The better would be if it can be done upon compilation. 

> I can do this right now, but it only takes the last one :-(

This happens because it's a map of responses distinct by a status code thus last one always wins.

**Comment by buehler** [comment]
Hey @juhaku

This is a delightful lib!

Are these features already released? I'm not able to use the content inside responses

Regards

**Comment by juhaku** [comment]
@buehler Not yet, but release is coming soon :slightly_smiling_face:
