### ISSUE TITLE
Support free-form additionalProperties

### ISSUE THREAD

**Issue by jacob-pro** [juhaku/utoipa#316]
A schema should be able to allow for free-form additional properties

See the documentation here: https://swagger.io/docs/specification/data-models/dictionaries/

In the YAML specification this would look like:

```yaml
    type: object
    additionalProperties: true
```

or 

```yaml
    type: object
    additionalProperties: {}
```

This doesn't currently seem to be supported by the existing [additionalProperties](https://docs.rs/utoipa/latest/utoipa/openapi/schema/struct.Object.html) field?

**Comment by juhaku** [comment]
True currently the free from additional properties is not supported. But a side thought is that why to have support for free form additional properties? Isn't it the same as without `additionalProperties` in a first place? Though if the free form additional properties must be supported then the syntax below can be supported quite easily. It only needs to have a support to define `ObjectBuilder::new()` as a value to the `additionalProperties` and the support is already implemented. 
> ```yaml
> type: object
> additionalProperties: {}
> ```

This might need some planning how the define this support. Probably there is need to support parsing some attribute over map fields e.g. `additional_properties = ...`. 

If we want to have free form supported with both styles `{}` and `true` then the [additionalProperites](https://docs.rs/utoipa/latest/utoipa/openapi/schema/struct.Object.html#structfield.additional_properties) should be changed to `serde_value::Value` type. But then we loose the strict schema which again is not preferred.

**Comment by jacob-pro** [comment]
> But a side thought is that why to have support for free form additional properties?

The reason for this is that it can be used to inform client code generators to add in a field to collect these additional values during deserialization.

I'm not hugely concerned about supporting both styles for my personal use; I just need one of them to work - but I guess it depends on how important it is to be able to deserialize a valid spec...

**Comment by juhaku** [comment]
Right. 

I'm fine with either support for both or just one of them. Probably if both should be supported then there is a need for another untagged enum e.g.
```rust
enum AdditionalProperites {
  FreeForm(serde_json::Value),
  Component(RefOr<Schema>),
}
```
This way the types would not be lost, but it also allows users to basically define what ever. Nonetheless it is according to spec though. Sort of I guess. 

I reckon it is better to support both sytax since in anyway the value need to be parsed from attributes somewhow. So then it could be like this.
```rust
struct Foo {
  #[schema(additional_properties = json!(true))]
  value: HashMap<String, String>,
}
```

```rust
struct Foo {
  #[schema(additional_properties = json!({}))]
  value: HashMap<String, String>,
}
```

**Comment by juhaku** [comment]
The support for the free form propertis is coming in next release. Though I checked here: https://swagger.io/docs/specification/data-models/data-types/ and while this states in _Free Form_ section that following definitions are equal. This would make one undestand that there is no need to define the `additionalProperties` in order to make it as a free form field.
```yaml
type: object

type: object
additionalProperties: true

type: object
additionalProperties: {}
```

However the PR #495 above will add `additional_properties` attribute to the `ToSchema` and `IntoParams` what if used will render spec in the second format as follows:
```yaml
type: object
additionalProperties: true
```
