### ISSUE TITLE
Data type refinement

### ISSUE THREAD

**Issue by gmarti** [juhaku/utoipa#328]
Hello !

Thanks for the library, we are really enjoying it

Is there a way to specify data type refinement keywords for an attribute with the schema macro ?
Like:
 - pattern: '^\d{3}-\d{2}-\d{4}$'
 - minimum: 1
 - maximum: 20
 - maxLength: 20
 - etc....
 
For example:
 #[schema(value_type = u16, minimum = 2, maximum = 20)]
or generically
 #[schema(value_type = u16, extras(minimum = 2, maximum = 20))]

**Comment by juhaku** [comment]
Hi, thanks it is my pleasure to build it :slightly_smiling_face: 

Unfortunately such attributes are not implemented yet. But surely need to be added. And will be added eventually. Of perhaps if there is interest to contribute to this then  be my guest :wink: 

Currently I haven't had any time to contribute to the library because of personal affairs taking too much time but it should get alleviated during next month.
