### ISSUE TITLE
ToSchema doesn't support slices

### ISSUE THREAD

**Issue by nkovacs** [juhaku/utoipa#381]
This fails with a [compiler error](https://github.com/juhaku/utoipa/blob/daa9f43f9f05cb8e2cc08f688cc8b26148004f12/utoipa-gen/src/component.rs#L85):

```
#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct Foo<'a> {
    pub arr: &'a [i64],
}
```

Unfortunately, value_type doesn't help

```
#[derive(Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct Foo<'a> {
    #[schema(value_type = Vec<i64>)]
    pub arr: &'a [i64],
}
```

Apparently because the default TypeTree is always evaluated, and only then replaced by the TypeTree from value_type.

I added `Type::Slice(array) => Self::get_type_paths(&array.elem),` [to the match](https://github.com/juhaku/utoipa/blob/daa9f43f9f05cb8e2cc08f688cc8b26148004f12/utoipa-gen/src/component.rs#L71) and it seems to work fine.

**Comment by nkovacs** [comment]
As for the value_type not helping, this fixes it: https://github.com/nkovacs/utoipa/commit/c4280adebfcb92eb0ad079c9d3aff8c627f51356
Although I'm not sure why the generic stuff only runs on the default type tree? Maybe that's also a bug and it should work on the value_type as well.

**Comment by juhaku** [comment]
That might be a bug, I need to check this out too, after I finnish one thing I am in middle of. It might well be that the slice's are not taken in account as the should. 

> Although I'm not sure why the generic stuff only runs on the default type tree? Maybe that's also a bug and it should work on the value_type as well.

True, good point. :thinking:  Most probably the generic and aliaces check should also happen from the override type as well. 

The `value_type` with `Vec<i64>` works because it will choose the `Group` or `Array` type from the match statements if I am not mistaken. I belive it is legit to add the support for `Type::Slice(...)` as well to the match statement.

**Comment by juhaku** [comment]
This is indeed bug, I'll try to fix this asap. Normally there should be no need to add `#[schema(value_type = ...)]` for slice or array fields a they should be recoginized by default as array types in OpenAPI.

**Comment by nkovacs** [comment]
Thanks!
