### ISSUE TITLE
/components/schemas/Value does not exist in document

### ISSUE THREAD

**Issue by GiKyouGetsu** [juhaku/utoipa#383]
Resolver error at components.schemas.*.properties.data.additionalProperties.$ref
Could not resolve reference: Could not resolve pointer: /components/schemas/Value does not exist in document

Does the schemas support the serde_json Value enum ? Or is there any work around ？

**Comment by juhaku** [comment]
In order a OpenAPI spec can be created for a type it must be static type. Serde's `serde_json::Value` is a dynamic type, we can pass any type we want during a runtime. If you want to use the `serde_json::Value` type then only way to get around this is to use `value_type` attribute.

Here is an example of `MyStruct` which is using `value_type` attribute to override the actual type to something else. `Object` here represents OpenAPI `type: object` which is basically anything. However utoipa could recognize the `Value` as is and directly map it as `Object` but this is not the case currently. Yet using a generic type like `Value` you loose the benefits of static types. 
```rust
#[derive(utoipa::ToSchema)]
struct MyStruct {
  #[schema(value_type = Object)]
  my_value: serde_json::Value
}
```

**Comment by GiKyouGetsu** [comment]
Working fine @juhaku , thanks for your acvice.....

**Comment by jayvdb** [comment]
This issue is regularly linked to.  Please note that since v3.3.0, utoipa supports `serde_json::Value`.  If you only want "an `object` with any contents", "Object" mentioned above is a good solution.  If your struct member field needs to contain a string or an int or an object, you need to use `Value`.
c.f. https://github.com/juhaku/utoipa/pull/568
If you need `Value`, and it isnt working for you, there may be more work to be done - lets investigate it.
