### ISSUE TITLE
Type aliases not being resolved correctly

### ISSUE THREAD

**Issue by dob9601** [juhaku/utoipa#429]
Using the type alias

```rust
pub type DateTimeUtc = chrono::DateTime<chrono::Utc>;
```

Leads to any serialized struct field having the type:
```js
{recursive: DateTimeUtc}
```

Directly specifying the type as `DateTime<Utc>` in the struct leads to the type being correctly resolved. (type shows as `date-time`)

**Comment by juhaku** [comment]
Hey,

This is because during parsing the AST we do not know what is the actual type of `DateTimeUtc` but we only know the type definition of the alias which in this case is the `DateTimeUtc`. This is then used to compare against know set of types to determine the the type and format for the field in the schema. That being said `DateTimeUtc` naturally will not match to any of predefined types. 

One alternative to type aliases here would be using a new type pattern, but that also adds another layer of indirection to the types. This would introduce another layer of boilerplate that one might need to implement for the new type to be able to access to the underlying type properties more elegantly.

Type aliases in general are quite hard thing in the utoipa world.

**Comment by juhaku** [comment]
@dob9601  There is now coming a new PR which adds global type aliases for `utoipa` #1048.
