### ISSUE TITLE
request_body type in #[path] is not required to exist

### ISSUE THREAD

**Issue by djrenren** [juhaku/utoipa#500]
It looks like the parameter to `request_body` is dumbly translated to a string. This means, if you write a non-existant type there, it will happily accept that.

We should emit even just a basic `use` that ensures the type exists.

**Comment by juhaku** [comment]
@djrenren 

`request_body` is not required as expected, because one might perform a request that does not have a request body as it is not required to exists in schema either. 

Yeah, currently there is no validation of any sort regarding the input value. Though this could be improved absolutely. I am currently working on related functionalities so I can take a look at this as well soon.

**Comment by juhaku** [comment]
Related https://github.com/juhaku/utoipa/issues/801
