### ISSUE TITLE
Support for OAS 3.1

### ISSUE THREAD

**Issue by Alfred-Mountfield** [juhaku/utoipa#531]
Apologies if this has been asked somewhere else, I have tried searching but GitHub's search can be difficult to tame..

Are there plans to support OpenAPI Spec 3.1 (if not already supported)? 

The code [seems to suggest](https://github.com/juhaku/utoipa/blob/61046d109f9e0254e430fb7e3d6fc2f651141502/utoipa/src/openapi.rs#L268) `utoipa` targets `3.0` at the moment but I couldn't find much mention of this in the README or anywhere else.

It would be great to be able to benefit from the full JSON Schema compatibility of the newest version of the OAS.

**Comment by juhaku** [comment]
> I have tried searching but GitHub's search can be difficult to tame..

Yeah I get that. :smile: 

> Are there plans to support OpenAPI Spec 3.1 (if not already supported)?

At the moment there is no support for 3.1 but it has been planned. However it not very high on priorities. Probably when redocly support will be added it might be useful to implement support for 3.1 simultaneously. Swagger UI does not support 3.1 spec at the moment, and I am not sure whether it ever will have support for it. 

3.1 support should be quite straight forward but there is certain cases that need to be taken in account like how to handle edge cases for both 3.1 and 3.0 so that users will still have the same experience no matter the API version target is. Most likely there will be crate feature flag to allow 3.1 support.

**Comment by juhaku** [comment]
Swagger UI has recently added support in their 5.0.0 version to the OpenAPI 3.1.0 spec. Perhaps soonish I could start working on with the utoipa support for this as well.

**Comment by Thomasdezeeuw** [comment]
@juhaku I was wondering if any progress is being made on supporting OpenAPI v3.1? I could use 3.1 support and are willing to help out to make progress.

**Comment by nicdard** [comment]
@juhaku do you still plan on supporting the version 3.1? To my knowledge, that is the only version where mutual TLS support was added, and Rocket is supporting it. I would like to generate the spec including the `mutualTLS` field so I can generate my client SDK, could you help me with this? I am willing to contribute the feature

**Comment by juhaku** [comment]
> @juhaku I was wondering if any progress is being made on supporting OpenAPI v3.1? I could use 3.1 support and are willing to help out to make progress.

> @juhaku do you still plan on supporting the version 3.1?

Yes, this has been little bit stalling for a while but it is now under work. 

Now there is a working progress branch for Open API 3.1 support. That will be massively breaking change compared to the existing Open API 3.0 version and will be part of next major release. There will be no simultaneous support for Open API 3.1 and 3.0 as that would be too much work thus most likely from next stable release onward only 3.1 will be supported.
