### ISSUE TITLE
Order of struct fields does not seem to be preserved even when using the preserve_order feature

### ISSUE THREAD

**Issue by johnperry-math** [juhaku/utoipa#561]
Issue #428 addressed the question of preserving the order of fields as declared in a struct, but when I add this feature to Cargo.toml, the fields are still sorted in the Schema.

For example, suppose I modify the todo-axum example's Cargo.toml so that we have:
```
utoipa = { path = "../../utoipa", features = ["axum_extras", "preserve_order"] }
```
...and main.rs so that we have this:
```
    /// Item to do.
    #[derive(Serialize, Deserialize, ToSchema, Clone)]
    pub(super) struct Todo {
        id: i32,
        #[schema(example = "Buy groceries")]
        value: String,
        checked: bool,
        done: bool,
    }

```
The result is that the fields are still in alphabetical order:
![image](https://user-images.githubusercontent.com/9720450/229828385-00006e88-2688-4e7a-89c5-67e7719d9c03.png)

Am I doing something wrong, have I misunderstood the purpose of that change, or is it something else entirely?

Similarly, is it possible to display the paths in the order they're declared in the `openapi` macro's `paths(...)` declaration?

**Comment by juhaku** [comment]
> Am I doing something wrong, have I misunderstood the purpose of that change, or is it something else entirely?

Hey, this seems to be regression bug in the `utoipa-swagger-ui`. If you print the schema as json to to console or file before you pass it to the `SwaggerUi` you should see correct behavior.  I believe this occurred due to changes here https://github.com/juhaku/utoipa/pull/502. 

I will fix as a next thing on my list.

> Similarly, is it possible to display the paths in the order they're declared in the `openapi` macro's `paths(...)` declaration?

This is not directly possible with utoipa since paths are sorted in UI itself. https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#display In order to sort paths you need to provide `operationSorter` attribute that is not supported by `utoipa-swagger-ui` by default at the moment.

**Comment by johnperry-math** [comment]
Thank you for the quickr response! Do you know when it will appear via `cargo update` or `cargo upgrade`?

**Comment by juhaku** [comment]
To my knowledge it should be already available since I have already released it to the crates. https://crates.io/crates/utoipa-swagger-ui

**Comment by johnperry-math** [comment]
Thanks, I can confirm it works :-)

**Comment by juhaku** [comment]
Great
