### ISSUE TITLE
Multi-Part Aliases / Identifiers for generics

### ISSUE THREAD

**Issue by c-thiel** [juhaku/utoipa#595]
First of all thanks for this awesome crate!

I currently have a struct with generics, very much like https://github.com/juhaku/utoipa/blob/489ddd663051a578e9285f5f4b5d87c0f626d6c0/examples/generics-actix/src/main.rs#L26-L31

I now need to expose a Variant under a multi-part identifier in the OpenAPI Spec, so instead of having plain `MyFloatObject` I would like to expose this object as `MyFloatObject::v1` for example.

Currently I can't find a simple way to do this, as `#[aliases]`  expects an identifier. In it's current implementation this is required because the alias is actually created as a rust type as well.

Is there a simple solution to this other than implementing the trait manually?

**Comment by juhaku** [comment]
> Currently I can't find a simple way to do this, as `#[aliases]` expects an identifier. In it's current implementation this is required because the alias is actually created as a rust type as well.

Yeah `#[aliases]` creates rust type aliases as well just so that they can be referenced within code as well. Perhaps the only way would be to create more aliases like `MyFloatObjectV1 = ....`. Or otherwise create the schema manually. At least I dont have any ideas how to do that. 

If the alias did accept a path instead of identifer we could not create rust type alias from a path. That would mean that we cannot use the type later on in another struct.
```rust
 #[derive(Serialize, ToSchema)] 
 #[aliases(v1::MyFloatObject = MyObject<f64>, MyIntegerObject = MyObject<u64>)] 
 pub struct MyObject<T: geo_types::CoordNum + PartialSchema> { 
     #[schema(schema_with=get_coord_schema::<T>)] 
     at: geo_types::Coord<T>, 
 }

struct Another {
    value: MyFloatObject // <-- not possible, because type does not exists
    value: v1::MyFloatObject // <-- not possible, because type does not exists
}
```

Though we could let the user be responsible of creating the alias when needed but the question is will they or is it just adding more boilerplate for them to implement manually? If user was responsible for creating the type alias itself then they could manually alter the type name of reference.

```rust
struct Another {
    #[schema(value_type =  v1::MyFloatObject)]
    value: MyFloatObject // <-- assuming user has created rust type alias named MyFloatObject and it exists in OpenAPI spec
}
```

Also another thing is the response with multiple content types of a same kind as demonstrated here: https://docs.rs/utoipa/latest/utoipa/derive.ToResponse.html and here https://docs.rs/utoipa/latest/utoipa/attr.path.html. There are examples of how to define multiple content types for a single response status with _`content`_ attribute.

**Comment by c-thiel** [comment]
For now, I will just go with defining it manually. Thanks for the insights!
Do you prefer to leave this open or close?

**Comment by juhaku** [comment]
> Thanks for the insights!

You are welcome :slightly_smiling_face: 

> Do you prefer to leave this open or close?

If we can agree that the issues is not actionable and / or the underlying issues is resolved, we can close it. (There are way too many open ones already :laughing: )

**Comment by c-thiel** [comment]
Yes, I would say its not actionable without Major breaking changes, so lets close this.
