### ISSUE TITLE
How to reference a response body containing a dictionary?

### ISSUE THREAD

**Issue by daviessm** [juhaku/utoipa#62]
I have a function which returns keys/values as Strings:

```javascript
{
  "key": "value",
  "key2": "value2",
  "key3": null
}
```

How can I represent this as a response body? I want to do something like 

```rust
/// Get all application options
///
/// Get a list of all application options from the database
#[utoipa::path(
    get,
    path = "/options",
    responses(
        (status = 200, description = "Sucessfully returned all application options", body = [Map<String, Option<String>>])
    )
)]
```

**Comment by juhaku** [comment]
Currently the the API does not know how to parse inline maps as type. This is indeed little incovenient since it tries to parse special format for the types of `request_body` or response `body` or parameter `type`. 

**Type parameter parsing explanation:**

* if type contains `[]` brackets, it is interpreted to be `slice` or `Vec`.
* if type is wrapped with `Option<MyType>` it is interpreted as optional. For optional `slice` or `Vec` type would then be `Option<[MyType]>`
* Otherwise the **type** can be `struct`, `enum` or `primitive type`

Workaround for this is to wrap the `Map<String, Option<String>>` to a new type and use it as argument to the response body. See the link https://doc.rust-lang.org/stable/rust-by-example/generics/new_types.html. As if I have understood how Rust works
using the newtype idiom does not add overhead to the application since rust compiler is smart enough to use inner type directly 
in compile time. 

To put this to a practice we can write the doc as follows:
```
#[derive(Serialize, Deserialize, Component)]
struct ApplicationOptionsMap(Map<String, Option<String>>);

#[derive(OpenApi)]
#[openapi(
     components(ApplicationOptionsMap)
)]
struct ApiDoc;

/// Get all application options
///
/// Get a list of all application options from the database
#[utoipa::path(
    get,
    path = "/options",
    responses(
        (status = 200, description = "Sucessfully returned all application options", body = ApplicationOptionsMap)
    )
)]
```

But becareful since in OpenAPI there is no way to give a type for a map. So maps will be serialized to OpenAPI doc as: `type: object` meaning they can contain arbitrary objects.

**Comment by daviessm** [comment]
Thanks, yeah, I came across this: https://swagger.io/docs/specification/data-models/dictionaries/ which shows how it's (not) implemented in OpenAPI. Obviously you can't implement it into utoipa if OpenAPI doesn't handle it so I'll close this.
