### ISSUE TITLE
Need help with utoipa::IntoResponses macro and unresolved document reference

### ISSUE THREAD

**Issue by ssosik** [juhaku/utoipa#623]
Hi! I'm really excited about your project, I've been looking for something like this for a while. Thank you for your work!

I'm hitting the following error in the Swagger UI while trying to use an error IntoResponses-derived enum:

> Resolver error at paths./v1/{domain}/{name}.get.responses.500.content.application/json.schema.$ref
> Could not resolve reference: Could not resolve pointer: /components/schemas/anyhow.Error does not exist in document

Enum
```rust
#[derive(thiserror::Error, Debug, utoipa::IntoResponses)]
pub enum AppError {
    /// 400 type errors, the user did something wrong, pass the error on to the user
    #[error("{0}")]
    #[response(status = BAD_REQUEST)]
    ValidationError(String),

    /// 403 type errors, the requested resource isn't allowed to be distributed
    #[error("unauthorized request")]
    #[response(status = FORBIDDEN)]
    Forbidden,

    /// 404 type errors, an underlying resource doesn't exist
    #[error("{0}")]
    #[response(status = NOT_FOUND)]
    NotFound(String),

    /// 500 type errors, all other errors  are internal and should return an opaque 500 to the user
    #[error(transparent)]
    #[response(status = INTERNAL_SERVER_ERROR)]
    UnexpectedError(#[from] anyhow::Error),
}
```

Utoipa::path attribute macro definition:
```rust
#[utoipa::path(
    get,
    path = "/v1/{domain}/{name}",
    params(selector::PathSelector),
    responses(
        (status = OK, response = datamodel::Object),
        AppError, // Use the AppError Enum for Error response variants
    ),
)]
pub async fn.....
```

I've been searching through other issues and digging through the docs, but I just can't figure this out. There are similar issues, but they all seem to be for the ToSchema derive.

Can you help me understand how I can resolve an anyhow::Error in the Schema document?

Thank you!!!

**Comment by juhaku** [comment]
Hey,

From the docs https://docs.rs/utoipa/latest/utoipa/derive.IntoResponses.html:
> Unnamed field struct decorated with [IntoResponses](https://docs.rs/utoipa/latest/utoipa/derive.IntoResponses.html) will by default create a response with referenced [schema](https://docs.rs/utoipa/latest/utoipa/trait.ToSchema.html) if field is object or schema if type is [primitive type](https://doc.rust-lang.org/std/primitive/index.html). #[to_schema] attribute at field of unnamed struct can be used to inline the schema if type of the field implements [ToSchema](https://docs.rs/utoipa/latest/utoipa/trait.ToSchema.html) trait. Alternatively #[to_response] and #[ref_response] can be used at field to either reference a reusable [response](https://docs.rs/utoipa/latest/utoipa/trait.ToResponse.html) or inline a reusable [response](https://docs.rs/utoipa/latest/utoipa/trait.ToResponse.html). In both cases the field type is expected to implement [ToResponse](https://docs.rs/utoipa/latest/utoipa/trait.ToResponse.html) trait.

The error occurs because the `anyhow::Error` is an external type and it does not have `ToSchema` implementation that is not registered to the `#[openapi(components(schemas(...)))]`.

To fix this we need to somehow implement `ToSchema` for the `anyhow::Error` and register it as a schema component. In this case the existing issues concerning the `ToSchema` will actually help to solve this as well.

Since we cannot directly implement the `ToSchema` for `anyhow::Error` we need to do it manually similarly to the serde's `with` attribute, but in `utoipa` there is `as` attribute.
```rust
#[derive(ToSchema)]
#[schema(as = anyhow::Error)]
struct Error {
  // ... implement fields that should exists in the anyhow::Error
}

// or alternatively if you want it to be represented as any type you can do following
#[derive(ToSchema)]
#[schema(as = anyhow::Error, value_type = Value)]
struct Error(anywho::Error)

#[derive(OpenApi)]
#[openapi(components(schemas(Error)))]
struct Doc;
```

Now you don't need to use the `Error` as an argument to the `UnexpectedError(#[from] anyhow::Error),` because of the `as` attribute. Also instead of `Value` there is also `Object` virtual type that renders as typeless schema object. However if you want to inline the schema of `anyhow::Error` instead of the default `$ref` then you need to actually use the custom `Error` as an argument to the enum variant in question. 

Another way is to manually edit the generated schema and use for example `PartialSchema` to create the schema for `anyhow::Error` and register it to the openapi.
```rust
fn foo() {
  let mut my_doc = Doc::openapi();
  let mut components = my_doc.components.get_or_insert(Components::default());
  let schema = String::schema(); // .. anyhow error is just a string
  
  components.schemas.insert("anyhow::Error", schema);
}
```

**Comment by ssosik** [comment]
Thanks for the detailed response. I'm still struggling to get this to work, but you've given some helpful advice.

**Comment by juhaku** [comment]
Anytime, :slightly_smiling_face:
