### ISSUE TITLE
Support for field deprecation without using #[deprecated]

### ISSUE THREAD

**Issue by nullsauce** [juhaku/utoipa#685]
Hi there,

Just a remark: It would be handy if it was possible to to mark a field `deprecated` in the spec, without having to use `#[deprecated]`, as it can generate spurious warnings.

Maybe a ` #[schema(deprecated)]` like below ?

```
#[derive(ToSchema)]
struct Foo {
  #[schema(deprecated)]
  bar: String
}
``

**Comment by juhaku** [comment]
So you would like to mark some field deprecated in OpenAPI spec, but not actually in code? Isn't that a bit counter intuitive? As what I consider very useful in Rust is that if you mark fields or generally anything `#[deprecated]` you get the warnings directly to your editor. This works as constant reminder that something should be migrated to another implementation? With that, then `utoipa` just follows the code base deprecation rules. Because if there is no warnings anywhere then at then end the parameters just get buried under the ever changing API. Though if the migration loop is long, it might become irritating to be constantly warned about things that are not actionable at the moment.

Nonetheless implementing this support is relatively small effort. And PR:s are welcome. My timeline is so congested that I am not able to provide any timeline for adding support for this unfortunately.

**Comment by juhaku** [comment]
> ...Hope it makes sense. 

Yeah, makes sense..

Great that you found the place where to make changes.
