### ISSUE TITLE
Add support for `IntoParams` to #[serde(flatten)]

### ISSUE THREAD

**Issue by ho-229** [juhaku/utoipa#695]
Hi, I found that `#[serde(flatten)]` is already supported by [ToSchema](https://docs.rs/utoipa/latest/utoipa/derive.ToSchema.html#partial-serde-attributes-support), but not by [IntoParams](https://docs.rs/utoipa/latest/utoipa/derive.IntoParams.html#partial-serde-attributes-support).

Do you have any plans?

**Comment by juhaku** [comment]
`IntoParams` having the `#[serde(flatten)]` support does not have any use because `IntoParams` is used only with struct params which fields are interpreted as query or path params. So far there hasn't been any plans to support this functionality and if it was to be implemented, it would need some planning first. To my understanding the `#[serde(flatten)]` on `IntoParams` would work differently than it does on `ToSchema`. This makes it hard to implement if even impossible. This is because on `ToSchema` it creates a combined schema using `allOf` schema. But `IntoParams` is not a schema but only a container in which each field is a schema.

**Comment by ho-229** [comment]
Thanks for answering
