### ISSUE TITLE
security header value name

### ISSUE THREAD

**Issue by myyrakle** [juhaku/utoipa#697]
I found a problem while writing documentation based on the example code.
![image](https://github.com/juhaku/utoipa/assets/16988115/bf4fd4ed-dd55-420b-9263-588ebec4fd2a)

Perhaps now, it seems that the header name is only created as "todo_apikey" in swagger ui.
![image](https://github.com/juhaku/utoipa/assets/16988115/f8d275f8-26f0-450f-8351-339fb070f4ec)

Maybe this part hasn't been implemented yet?
If so, I have an idea to contribute.

**Comment by juhaku** [comment]
I am sorry, but I don't quite get what is the actual issue here? `api_key` there is only the name of the security schema to use which must match to security schema in the `components`. Then that security schema defines the actual specification of what kind of security is being expected for then endpoint. E.g. in this case header named `todo_apikey` is expected. Typically if the authorization is any type of api key or bearer token the scopes are superfluous. They are usually used with oauth flows.

**Comment by myyrakle** [comment]
ah! I guess I'm confused. 

I will close the issue.
