### ISSUE TITLE
Converting nested Json to nested QueryParams, Vec in particular

### ISSUE THREAD

**Issue by AlexStorm1313** [juhaku/utoipa#718]
I'm having trouble converting nested Json that contains a Vec to nested QueryParams. I believe parsing nested queryparams does not really have a default spec so the output that swagger produces currently is this:
![image](https://github.com/juhaku/utoipa/assets/5901188/bf7a1fd1-3dcc-4405-a997-30aa98f3ea78)

```
?child[example_vec]=val1&child[example_vec]=val2
```

That is derived from these structs:
```
#[derive(Debug, Clone, ToSchema, IntoParams, Serialize, Deserialize)]
struct Parent {
    pub child: Option<Child>
}

#[derive(Debug, Clone, ToSchema, IntoParams, Serialize, Deserialize)]
struct Child {
    pub example_vec: Option<Vec<String>>
}
```
But what I like the result to be is this:
```
?child[example_vec][0]=val1&child[example_vec][1]=val2
```

is it possible to define this behavior and if so how? I tried setting `style = DeepObject` tried some serde options but I can't seem to figure it out. The library that I'm using to serialize the QueryParams is `serde` with `serde_qs`

**Comment by juhaku** [comment]
Not sure whether it fully works. If the `serde_qs` does something more to parsing and resolving query parameters than default `serde` with regular JSON structured objects, it surely is not implemented and taken into account in `utoipa`. 

To my understanding `utoipa` should work with deep objects as what comes with sending JSON objects as query parameters but this is really untouched area of development in `utoipa`. And I have no knowledge about `serde_qs` and becaue of  that, implementing the support for `serde_qs` would be quite hard to do. Perhaps the first question to ask is, that does the `serde_qs` produce a query string variables the way it is OpenAPI standard suitable? If not then the support cannot be added at least from the parts that it is not applicable to the OpenAPI standard. Otherwise of course PRs are welcome if there is interest in providing such functionality to the `utoipa`.

**Comment by AlexStorm1313** [comment]
Thanks!
