### ISSUE TITLE
Swagger ui not working

### ISSUE THREAD

**Issue by shellking4** [juhaku/utoipa#731]
Swagger Ui is not working. Please is this intended or I'm doing something wrong ?
I get this message in the browser when I hit the swagger docs url ``` wrong number of parameters: 0 expected 1 ``` And I get 404 in console.

**Comment by ilha** [comment]
I'm seeing the same issue here with the latest 3.5.0 version of utoipa and swagger-ui 3.1.5

**Comment by shellking4** [comment]
As for me I got it working by having this in my Cargo.toml

utoipa-swagger-ui = { version = "3", features = ["debug-embed", "actix-web"] }

Also be sure not to forget the trailing slash at the end of the URL.

http://localhost:8000/swagger-ui/ (the trailing slash is important)

I don't understand why it not possible to fully customise the urls and still have it working.

**Comment by ilha** [comment]
Yep, that also did the trick for me. Thank you.

**Comment by juhaku** [comment]
One could try to change the URL as follows to serve Swagger UI without the last slash `/`.
`SwaggerUi::new("/swagger-ui{_:.*}")`. **Note!** After the `swagger-ui` there is no slash. However I'm not sure whether this actually will work. This is in actix-web, for other frameworks this will be different if even possible.

You can change the URL for the `SwaggerUi` as you wish and also the URLs where the OpenAPI spec will be served from, but you need to change the `Config` for the Swagger UI also accordingly. See more about the topic here https://github.com/juhaku/utoipa/pull/274.

But in short the `SwaggerUi` is designed to work from root of the web server, thus nesting will be quite difficult e.g. serving the Swagger UI  from nested / sub router. This is because the `SwaggerUi` will create the operation handlers according to the given URLs.  

So as seen in the example below. The handler for Swagger UI will be created for the `/swagger-ui/...rest`  and the OpenAPI spec will be served from `/api-docs/openapi.json`. If this router / service config is to be nested under path `/v1` then the SwaggerUi will be served from `/v1/swagger-ui/...rest` and the OpenAPI spec from `/v1/api-docs/openapi.json`. But because of `.url("/api-docs/openapi.json"...)` the Swagger UI does not know that the ApiDoc is actually served with  prefix `/v1/..`. In order to make `SwaggerUi` to know about this nested routing we need to change the config for the Swagger UI manually. 
```rust
SwaggerUi::new("/swagger-ui/{_:.*}")
  .url("/api-docs/openapi.json", ApiDoc::openapi())
```

Let the Swagger UI know that the OpenAPI spec is served from different route than to the one given to the `.url(...)` method call.
```rust
let config = Config:from("/v1/api-docs/openapi.json");
SwaggerUi::new("/swagger-ui/{_:.*}")
  .url("/api-docs/openapi.json", ApiDoc::openapi())
  .config(config)
```
