### ISSUE TITLE
utoipa::path proc_macro with additional actix route proc_macro attibutes causes compilation error

### ISSUE THREAD

**Issue by Weshnaw** [juhaku/utoipa#75]
It seems the the utoipa::path does not take into account the fact actix route proc_macros can have additional attributes, I discovered it when attempting to use the wrap attribute, but it seems to cause issue with any attribute or more specifically the `,` used to add additional attributes

Take the route:
```
/// Get Todo by given todo id.
///
/// Return found `Todo` with status 200 or 404 not found if `Todo` is not found from shared in-memory storage.
#[utoipa::path(
    responses(
        (status = 200, description = "Todo found from storage", body = Todo),
        (status = 404, description = "Todo not found by id", body = TodoError)
    ),
    params(
        ("id", description = "Unique storage id of Todo")
    )
)]
#[get("/todo/{id}")]
pub(super) async fn get_todo_by_id(id: Path<i32>, todo_data: Data<TodoData>) -> impl Responder {
    let todos = todo_data.todos.lock().unwrap();
    let id = id.into_inner();

    match todos.get_one(id) {
        Ok(todo) => todo.response(),
        Err(error) => error.response(),
    }
}
```
And lets say we wanted to add a middleware with the wrap attribute:
```
/// Get Todo by given todo id.
///
/// Return found `Todo` with status 200 or 404 not found if `Todo` is not found from shared in-memory storage.
#[utoipa::path(
    responses(
        (status = 200, description = "Todo found from storage", body = Todo),
        (status = 404, description = "Todo not found by id", body = TodoError)
    ),
    params(
        ("id", description = "Unique storage id of Todo")
    )
)]
#[get("/todo/{id}", wrap = "ApiKeyAuthenticator")]
pub(super) async fn get_todo_by_id(id: Path<i32>, todo_data: Data<TodoData>) -> impl Responder {
    let todos = todo_data.todos.lock().unwrap();
    let id = id.into_inner();

    match todos.get_one(id) {
        Ok(todo) => todo.response(),
        Err(error) => error.response(),
    }
}
```
It will cause a compiler error:
```
error: unexpected token
   --> src\controllers\todo.rs:189:19
    |
189 | #[get("/todo/{id}", wrap = "ApiKeyAuthenticator")]
    |                   ^
```

vs without the utoipa proc_macro
```
#[get("/todo/{id}", wrap = "ApiKeyAuthenticator")]
pub(super) async fn get_todo_by_id(id: Path<i32>, todo_data: Data<TodoData>) -> impl Responder {
    let todos = todo_data.todos.lock().unwrap();
    let id = id.into_inner();

    match todos.get_one(id) {
        Ok(todo) => todo.response(),
        Err(error) => error.response(),
    }
}
```
```
Compiling playground-api v0.1.0 (C:\Users\bfall\Development\Rust\playground-api)
Finished dev [unoptimized + debuginfo] target(s) in 3.12s
```

**Comment by juhaku** [comment]
Oh snap. Somehow I have missed that. I tried to look from docs all the possibilities it could take as arguments but didn't find for some reason. To overcome this issue for now you can disable `actix_extras` feature but then you need to define the `path` and `operation` within `#[utoipa::path()]` macro. 
```rust
#[utoipa::path(
    get,
    path = "/todo/{id}",
)]
```
This is definitely bug clear as glass. I will fix it to the next release. Thanks for pointing out.

**Comment by Weshnaw** [comment]
While on this topic I wonder if it would be possible to get something like the `utoipa::path(...security(...))` information from the , `wrap = "ApiKeyAuthenticator")` 

Though, I'm sure that's easier said then done, if even feasible, or honestly if it would even be a useful abstraction.

**Comment by juhaku** [comment]
That is an interesting topic indeed. It would be quite cool to get that information from that wrap attribute. Though I'm afraid that it is actually next to impossible to do so. As that would require examining ast code of no particular structure since the actual implementation would always be written by the developer of the api. This leads to nightmare of trying to guess what kind of security the user is actually implementing even so because there is more security options to consider as well which are also 
supported.

Although there could be 2 ways to complete this but neither of them would really improve the situation. 
a) If we can enforce the `ApiKeyAuthenticator` to implement some trait (let's say `AuthProvider`) that could be called which then would return the information the `security(...)` section would need that would be doable. However only it would change the `security(...)` section stuff now to separate trait.
b) The `ApiKeyAuthenticator` could have derive macro of some sort wich could be parametrised in similar fashion as now the `#[utoipa::path(...security(...))]` and there would be a way to get access to those macros we could do that. But again that only would change the location of the security declaration to another place. 

Both of these are kind of not worth seeing the trouble because it would make things even more complicated without actual benefit. 

However the `security(...)` can also be defined api wide with the `openapi(...security(...))` as well.
