### ISSUE TITLE
Sort API methods in utoipa-swagger-ui: custom Swagger UI initializer

### ISSUE THREAD

**Issue by robot518** [juhaku/utoipa#765]
like this https://stackoverflow.com/questions/24951268/sort-api-methods-in-swagger-ui

how to do?

**Comment by matthiasg** [comment]
I think this is a pretty big deal. In order for long lists of routes to make any sense some sort order needs to be definable. Either source order (which is derivable from the macros) or some sort key

**Comment by matthiasg** [comment]
@juhaku this seems basically closed with feature preserve_path_order for me

**Comment by juhaku** [comment]
@robot518 Since the `utoipa-swagger-ui` has been supporting for a while overriding the content you could basically do that custom initialization. https://github.com/juhaku/utoipa/tree/master/utoipa-swagger-ui#build-config

The default loader `swagger-initializer.js` looks as follows. Utoipa will replace from url to presets with `{{config}}` which will be dynamically provided by the `utoipa-swagger-ui`. Rest of the files can be changed as one sees fit. E.g. You could add custom sorting and change JS as one like or styles perhaps.
```js
window.onload = function() {
  //<editor-fold desc="Changeable Configuration Block">

  // the following lines will be replaced by docker/configurator, when it runs in a docker-container
  window.ui = SwaggerUIBundle({
    url: "https://petstore.swagger.io/v2/swagger.json",  // * utoipa will replace
    dom_id: '#swagger-ui',                               // * these 
    deepLinking: true,                                   // * lines with {{config}}
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  });

  //</editor-fold>
};
```
