### ISSUE TITLE
API versioning and basepath

### ISSUE THREAD

**Issue by danwilliams** [juhaku/utoipa#768]
It does not seem possible to support API versioning in utoapi at present. There are a number of approaches that I am aware of, including generating multiple OpenAPI schemas and supplying a basepath to OpenAPI.

I don't see support for the OpenAPI basepath in utoapi and so being able to say, "all my endpoints are under X basepath" is not currently possible.

I also don't see any way of generating multiple schemas using utoapi, although this is in any case not ideal as they would mount up over time.

What is the recommended approach to managing API versions using utoapi at present? For instance, if I have both `/api/v1/foo` and /api/v2/foo` then what is the best way to organise this so that utoapi produces clear OpenAPI documentation?

Are these things on a roadmap somewhere for future support?

**Comment by juhaku** [comment]
Currently there are 2 ways to actually solve this. The `#[utoipa::path(...)]` macro has `context_path` attribute. that can be used to prepend the path. Though this is currently bit cumbersome because it need to be given for each path.

Another way is to use the `Server` property in OpenAPI spec. E.g. creating couple of servers one for `/api/v1` and another `/api/v2`. The servers can be put globally to the API or to the `PathItem` itself but there is no macro support for setting up servers to the path.

This would need some improvement, but there is no any convenient way to group paths together e.g. scoping because also the requirements for such are different for each framework.

**Comment by akashlama1998-icloud** [comment]
I'm interested in this too.. Is this being worked on?

**Comment by R3dByt3** [comment]
I would also be interested in this feature, at first glance rust seems to be a possible rising star for APIs and swagger is usefull for documentation and testing these. API versioning seems like a must have to me and workarounds never feel great.

+1 for the proposal of @ctron

**Comment by juhaku** [comment]
In master, ultimately landing in 5.0.0 release, there will be nesting functionality to nest other APIs to one.
https://github.com/juhaku/utoipa/blob/f6d1c3d059e4b42ebcbedfbd98241a51f7991014/examples/axum-utoipa-nesting-vendored/src/main.rs#L13-L20

**Comment by juhaku** [comment]
> Defining multiple swagger endpoints might feel weird, but by omitting the "use_base_layout()" method and providing multiple swagger json urls it looks like the swagger UI creates a nice drop down to select the desired api version.
>
>```rust
>    let swagger_config = Arc::new(utoipa_swagger_ui::Config::new([
>        "/v1/swagger.json",
>        "/v2/swagger.json",
>    ])
>```

@R3dByt3 Yes that is basic functionality from Swagger UI. As demonstrated in example below you can also directly tell Swagger UI to use multiple different OpenAPI docs. Then it is just matter of defining what `ToSchema` implementations gets added to what openapi. In addition shown above nesting with `nest(...)` can be also used to control the different versions of schemas and paths.
https://github.com/juhaku/utoipa/blob/576f6c129010b4f6e6445c06393cfcf2cfee30df/examples/actix-web-multiple-api-docs-with-scopes/src/main.rs#L27C13-L36C16

To these words I would conclude this task as solved. If there are more matters to consider, this can be reopened.
