### ISSUE TITLE
Support for `description` and `summary` attributes on `#[utoipa::path]` macro.

### ISSUE THREAD

**Issue by mortifia** [juhaku/utoipa#781]
https://swagger.io/specification/?sbsearch=description#path-item-object

in `#[utoipa::path()]`

when i add description or summary
`unexpected identifier, expected any of: operation_id, path, get, post, put, delete, options, head, patch, trace, connect, request_body, responses, params, tag, security, context_path`

**Comment by juhaku** [comment]
That is by design. There is no `description` nor `summary` attributes on `#[utoipa::path]` macro. The description and summary is currently only resolved from the doc comment above the handler function. There has been a request for having support for these values as attributes on `#[utoipa::path]` path macro. This is something that can be added in  future.

Relatead https://github.com/juhaku/utoipa/issues/439

**Comment by juhaku** [comment]
I have now implemented support for the `description = ...` and `summary = ...` attributes here #948
