### ISSUE TITLE
DELETE operations cannot have a requestBody

### ISSUE THREAD

**Issue by UVUUUVUU** [juhaku/utoipa#800]
When I want to do some batch delete operation, for example, I want to delete some users, but some error occurred. It looks like I have to put the user ids in the path, and DELETE operations cannot have a requestBody. How can I solve this? thanks.
```
Semantic error at paths./api/user.delete.parameters.0.name
Path parameter "ids" must have the corresponding {ids} segment in the "/api/user" path
Jump to line 979
Semantic error at paths./api/user.delete.requestBody
DELETE operations cannot have a requestBody.
Jump to line 990
```
example code: 
```
pub struct DeleteStruct {
    pub ids: Vec<i32>,
}
#[utoipa::path(
    context_path = "/api",
    responses(
        (status = 200, description = "OK", body = Struct1)
    ),
    params(DeleteStruct,)
)]
#[delete("/user")]
pub async fn delete_rules(
    req: HttpRequest,
    request: web::Json<DeleteStruct>,
) -> HttpResult {}
```

**Comment by juhaku** [comment]
The DELETE same as GET by spec definition (http standard specification) does not state clearly whether you can have body or not and in what form. The common semantic is that DELETE and GET request does not specify body. Moreover some libraries and languages does not even support specifying body for DELETE or GET requests. That is also the reason the utoipa does not support specifying body for them as well.

There are 2 options to choose from.
1. Use POST request for such an operation instead of the DELETE
2. Specify the arguments as query parameters for the DELETE request. 

As the OpenAPI specification states: https://swagger.io/specification/#operation-object it should be avoided if possible.
> The request body applicable for this operation. The requestBody is fully supported in HTTP methods where the HTTP 1.1 specification [RFC7231](https://tools.ietf.org/html/rfc7231#section-4.3.1) has explicitly defined semantics for request bodies. In other cases where the HTTP spec is vague (such as [GET](https://tools.ietf.org/html/rfc7231#section-4.3.1), [HEAD](https://tools.ietf.org/html/rfc7231#section-4.3.2) and [DELETE](https://tools.ietf.org/html/rfc7231#section-4.3.5)), requestBody is permitted but does not have well-defined semantics and SHOULD be avoided if possible

The utoipa does not necessarily restrict users from defining request body for DELETE method but OpenAPI spec validation libraries does so.

**Comment by UVUUUVUU** [comment]
Ok, got it. Thanks for your answer!
