### ISSUE TITLE
`chrono::Duration` causes error "Expected doc attribute with one path segment"

### ISSUE THREAD

**Issue by SeriousBug** [juhaku/utoipa#85]
Hi, the following code causes a build error:

```rust
#[derive(Serialize, Component)]
struct Stats {
    #[serde(serialize_with = "serialize_duration")]
    pub uptime: Duration,
}

#[utoipa::path(
    responses(
        (status = 200, description = "Uptime", body = [Stats]),
    ),
)]
#[get("/stats")]
#[tracing::instrument(skip(state))]
async fn get_stats(state: web::Data<AppState>) -> web::Json<Stats> {
    web::Json(Stats {
        uptime: chrono::Local::now() - state.started_at,
    })
}
```
This causes the error `Expected doc attribute with one path segment` for the utoipa instrumentation. This is with actix-web:

```toml
actix-web = "4.0"

utoipa = { version = "0.1.2", features = [
  "actix_extras",
  "debug",
  "chrono_types_with_format",
] }
```

The same error also happens with `chrono_types` feature, or with the chrono feature disabled.

**Comment by juhaku** [comment]
Hello, what if you try to remove the `#[tracing...]` macro from the function? In case it occurs with or without the `chrono` features enabled it should not be directly connected to the features itself. The error itself means that when the Rust compiler compiles those macros the `utoipa-gen` is trying to find the doc comments from various places like above the `get_stats` function, above the `Stats` struct or above the `uptime` field. And it fails to do so because of incorrectly formatted doc attribute macros, which should never happen though. Are you able to pinpoint which lines causes the compiler not to co-operate? Is it the `get_stats` or the `Stats` struct?

I could make it not a hard error if the doc-comment macro generated or otherwise is is malformed though. But not sure whether it would fix anything and only move the error further in the rabbit hole becuase not knowing exactly what causes this mailfunction.

Also to test this out I tried this with the actix-todo example from utoipa-repository with code and it does work issues.
```rust
#[derive(Serialize, Component)]
struct Up {
    #[serde(serialize_with = "duration_serialize_str")]
    up: Duration,
}

pub fn duration_serialize_str<S>(d: &Duration, serializer: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{
    serializer.serialize_str(&d.to_string())
}

#[utoipa::path(
    responses(
        (status = 200, description = "Get duration", body = Up)
    )
)]
#[get("/up")]
async fn up() -> web::Json<Up> {
    web::Json(Up {
        up: Duration::zero(),
    })
}
```
And the api doc as well. I removed the unnecessary parts from the declaration.
```rust
 #[derive(OpenApi)]
    #[openapi(
        handlers(
            up
        ),
        components(Up)
    )]
    struct ApiDoc;
```

```rust
 HttpServer::new(move || {
        App::new()
            .service(up)
            .service(
                SwaggerUi::new("/swagger-ui/{_:.*}")
                    .url("/api-doc/openapi.json", ApiDoc::openapi()),
            )
    })
```

And btw, you can use bracketed body  `body = [Stats]` when you want to response body to be slice or Vec, And use raw type when you want to return object `body  = Stats`.

**Comment by juhaku** [comment]
#86

**Comment by juhaku** [comment]
You can now try whether it works with using reference to master in your Cargo.toml file:
```
utoipa = { git = "https://github.com/juhaku/utoipa", branch = "master", features = [
  "actix_extras",
  "debug",
  "chrono_types_with_format",
] }
utoipa-swagger-ui = { version = "0.2", git = "https://github.com/juhaku/utoipa", branch = "master", 
  features = ["actix-web"] }
```

**Comment by SeriousBug** [comment]
Oh that's embarrassing, removing the trace macro fixed the issue. It worked in other functions that had the macro so I didn't think it would be the cause. Thanks so much for your help, and thanks for building this!

**Comment by juhaku** [comment]
Good that you got it working. Happy to help and great its found to be useful :)
