### ISSUE TITLE
Request for Changelog

### ISSUE THREAD

**Issue by thor314** [juhaku/utoipa#915]
Dependabot submitted a PR to my repo, as Utoipa has updated version from 3 -> 4, but I'm not sure what changed. Requesting a change log for this repo for developers to scan when updates occur.

**Comment by izolyomi** [comment]
I've recently found this awesome library, thank you for the implementation efforts.

Without any changelog available, I also feel like left in the dark while trying to decide the right version to depend on (4.x vs recent 5-rcx), knowing that there might be lots of breaking changes but having no information on the actual differences.

**Comment by juhaku** [comment]
Yes I agree perhaps a change log file would be good for quick reference for users to see what actually has changed. I will most likely collect a list of breaking changes from 3 to 4 and 4 to 5 and write a change log file from it later on (probably before the releases of the 5.0.0). 

The 5.0.0 will be breaking from multiple aspects compared to 4.x.x like it will be OpenAPI 3.1 only and other changes to the API itself which will flesh out as the time goes by.

> Dependabot submitted a PR to my repo, as Utoipa has updated version from 3 -> 4, but I'm not sure what changed. Requesting a change log for this repo for developers to scan when updates occur.

The only breaking change from 3 to 4 is described here #762, this actually should not even break anyone's code, unless you are a library author. It is counted as breaking change since it changes the outward API by changing the `Path` trait definition.

**Comment by jayvdb** [comment]
The releases entries do contain a list of changes, e.g. https://github.com/juhaku/utoipa/releases/tag/utoipa-4.2.3

I thought Dependabot supported extracting change entries from Releases.

renovate does.

**Comment by juhaku** [comment]
I have homegrown solution for the resolving the changes since it is not that hard to actually parse it from the git log.

**Comment by juhaku** [comment]
Crate specific changelogs are now available #1075
