### ISSUE TITLE
nest(...) attribute doesn't existin last utoipa-gen 4.3.0 crate

### ISSUE THREAD

**Issue by ifree92** [juhaku/utoipa#950]
Hi there,

I'm very excited about a new [nest(...) feature](https://github.com/juhaku/utoipa/releases/tag/utoipa-swagger-ui-7.0.2).

But seems the `utoipa-gen` with the recent changes has not been pushed.

https://docs.rs/utoipa-gen/4.3.0/utoipa_gen/derive.OpenApi.html - there's no `nest(...)`

I see it was added in sources: https://github.com/juhaku/utoipa/blob/master/utoipa-gen/src/openapi.rs#L123 but probably forgot to increment a version https://github.com/juhaku/utoipa/blame/master/utoipa-gen/Cargo.toml#L4

**Comment by juhaku** [comment]
Ah, that thing, the feature you see in master and in examples is from master branch that is not released thus not available. The `utoipa-swagger-ui` release page show that `nest()` support has been released just because that commit has changes to the `utoipa-swagger-ui/Cargo.toml` file (I should not have added that change). However in reality that feature concerns only `utoipa` and `utoipa-gen` and those are not released since there will be more change that I want to add before making a release.
