### ISSUE TITLE
utoipa-rapidoc causes panic on axum due to empty path

### ISSUE THREAD

**Issue by hutchisr** [juhaku/utoipa#953]
When trying to use rapidoc with axum as per the example docs:
```rust
axum::Router::new()
        .merge(RapiDoc::with_openapi("/rapidoc", ApiDoc::openapi()))
```

The application will panic with ```Paths must start with a `/`. Use "/" for root routes``` due to the `RapiDoc`'s `path` being an empty string.

This can be worked around with something like `RapiDoc::with_openapi("/rapidoc", ApiDoc::openapi()).path("/")` which will serve the UI from "/" and the spec from "/rapidoc". This should probably be changed or at least mentioned in the docs though a `with_url` function like utoipa-redoc would also be nice.

**Comment by juhaku** [comment]
> RapiDoc also breaks when nesting the created router under any other path.

Nesting does not work because it will create a handler from root to serve both the UI and the spec in separate paths and it does not have a clue about the root where the `RapiDoc` instance is being placed. This said it does not know whether `RapiDoc` is placed under the root of the API or some nested path and there is no way to know that. To allow nesting `RapiDoc` it would first need to know about the path it is in.  Thus the `nest` call would become something like this `.nest("/nested/path", RapiDoc::with_openapi("/rapidoc", ApiDoc::openapi()).nested("/nested/path"))`

**Comment by juhaku** [comment]
@hutchisr Right, that empty path issue should be quite easy fix and could be fixed for the next release.
